### ISSUE TITLE
need new hex function so colorString can colored on IDE

### ISSUE THREAD

**Issue by raiscui** [rtfeldman/elm-css#101]
![image](https://cloud.githubusercontent.com/assets/857943/14167276/905bbf9c-f74c-11e5-9485-86580f46b9d8.png)

it's useful, just make new hex' or hexStr , the code is very simple, I already have，but I think more people   will like this

**Comment by eeue56** [comment]
Couple of things:

- Why do you need this?
- How does adding a function that does pretty much nothing new help?
- If you can make it, open a PR.

**Comment by raiscui** [comment]
I make a PR. #102
