### ISSUE TITLE
Errors when adapting the example for my project

### ISSUE THREAD

**Issue by SandiDusic** [rtfeldman/elm-css#104]
For starters, [this example code](https://github.com/rtfeldman/elm-css/blob/1.1.0/examples/src/HomepageCss.elm) uses a module which does not exist, namely Css.Namespace, which seems to be replaced by Html.CssHelpers. This lead me to believe the example is outdated (though it compiled to Css just fine with elm-css).

I took files from that project and changed them around to fit my needs. This file holds my main (and only) stylesheet:
```
module MainStylesheet (css) where

import Css exposing (..)
import Css.Elements exposing (..)
import SharedStyles exposing (..)


css: Css.Stylesheet
css =
    (stylesheet << mainNamespace)
    [ ((.) Term)
        [ color (rgb 255 0 0) ]
    , ((#) MouseManipulator)
        []
    ]
```

This is the error it complains with:
```
The right argument of (<<) is causing a type mismatch.
(<<) is expecting the right argument to be a:
    a -> List Snippet
But the right argument is:
    { class : List a -> Html.Attribute
    , classList : List ( a, Bool ) -> Html.Attribute
    , id : b -> Html.Attribute
    , name : String
    }
Hint: I always figure out the type of the left argument first and if it is
acceptable on its own, I assume it is "correct" in subsequent checks. So the
problem may actually be in how the left and right arguments interact.
```
Honestly I have no idea how that function composition is supposed to work since namespaces aren't functions at all! The README cites this usage:
`(stylesheet << namespace "dreamwriter")`
So the RHS is supposed to be a namespace, but that just won't compile. Removing the composition and just passing the list of snippets directly to `stylesheet` works, but how then are the ids and classes supposed to be namespaced?

**Comment by altaic** [comment]
+1

**Comment by SandiDusic** [comment]
This works in 0.17.
