### ISSUE TITLE
Generating style sheets at runtime

### ISSUE THREAD

**Issue by kof** [rtfeldman/elm-css#106]
I wonder if it makes sense for elm-css to opt in generating style sheets at runtime (I am the author of [jss](https://github.com/jsstyles/jss)). It brings a number of benefits:

- Smaller CSS payload (up to 50%). Things like [vendor prefixer](https://github.com/postcss/autoprefixer) and [autoreset](https://www.npmjs.com/package/postcss-autoreset) and mixing rules using elm (same for all server-side CSS preprocessing languages) will most likely result in redundant CSS.
- Build tool agnostic, anything that works for js.
- Lazy rendering. Only render style sheets that are in use by rendered components.
- Code sharing between sheets and elm  doesn't results in duplication in compiled files.
- Possibility for a more advanced logic when targeting specific platforms and devices. For e.g. styles which consider pixel density, resolution, device type and any other specific feature/setting at the same time.

**Comment by eeue56** [comment]
You can already do it at runtime.

**Comment by eeue56** [comment]
There's no requirement to use the CLI tool at all

**Comment by kof** [comment]
So it renders a style sheet? or inline styles?

**Comment by eeue56** [comment]
It renders CSS, what you do with it after that is up to you. Stick it in a style tag, or make it render as a stylesheet. Also possible to use as inline styles. http://package.elm-lang.org/packages/rtfeldman/elm-css/1.1.0/Css#compile

**Comment by kof** [comment]
Thanks.

**Comment by eeue56** [comment]
@kof is this everything you needed?

**Comment by kof** [comment]
So it has no abstraction for working with a CSS string at runtime: attaching/detaching to/from dom when component mounts, modifying rules at runtime, applying vendor prefixes and other things for e.g. jss does.

I think it might play well together, but I am not deep enough in elm and elm-css right now.

**Comment by eeue56** [comment]
> So it has no abstraction for working with a CSS string at runtime: 

> attaching/detaching to/from dom when component mounts

We don't have this concept in Elm. When a component is rendered in the view, it is totally possible to attach the CSS then however.

> modifying rules at runtime

This is totally possible and dead easy. You just have to use that function I linked, instead of using elm-css as a server-processed language and instead one in the browser. Very very very easy.

> applying vendor prefixes and other things 

It is trivial to do this for Elm-css and it has been rewritten in a way to make this simple. @lukewestby was working on this.

**Comment by kof** [comment]
Interesting, I def. need to play with it, sounds to good)
