### ISSUE TITLE
Clear keywords and clearfix

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#111]
Path to a "batteries included" `clearfix` implementation:
- [ ] Everything under MDN docs for `clear`: https://developer.mozilla.org/en-US/docs/Web/CSS/clear
- [ ] `display: table`
- [ ] Uncomment [`clearfix`](https://github.com/rtfeldman/elm-css/blob/f84f908e24dc9a0c46fb294cff11c83adfbdf267/src/Css.elm#L4700-L4715), expose it, and add tests

**Comment by Dremora** [comment]
Just out of curiosity, is there really a need for clearfix to be implemented as part of this library? Flexbox can do it without hacks, is easier to use and has [great browser support](http://caniuse.com/#feat=flexbox).
Another reason against this is the nature of mixins: they bring extra behaviour in the current context. Imagine using this mixin and trying to use `::after` pseudo-element — the two won't work together. Or worse: if the mixin's implementation changes, it could cause issues in the previously working code.

**Comment by zazaian** [comment]
I see that this is still open: does clearfix still need to be implemented here? Are there any prevailing thoughts as to why this shouldn't be implemented? There's an article [here](http://www.cssmojo.com/clearfix_block-formatting-context_and_hasLayout/) that suggests `display:inline-block` in conjunction with `overflow:hidden`, but I much prefer using clearfix for more complex floats and behaviors.

I'd be happy to implement this if this is dangling and nobody wants to jump on it. I needs me some `clearfix`.

**Comment by rtfeldman** [comment]
I'm leaning toward @Dremora's point of view on this. I think it might make more sense as a separate package.

It's not lost on me that the idea of "minimizing API surface area" on this particular library is sort of comically unattainable, but I like the idea of keeping its scope as close to "the widely supported parts of the CSS spec, and that's it" as possible. In retrospect, `clearfix` probably should have been out of scope even though I'd personally like to use it too. 😉 

I'm gonna close this, but @zazaian if you want to release a separate package, I'd be happy to link to it from the README here!

**Comment by zazaian** [comment]
Hey there @rtfeldman - so I support the idea that the `clearfix` itself is sort of hacky, and as basically just a hacky CSS selector it really doesn't belong in a library whose purpose is to model the CSS spec effectively.

That said, I would strongly consider adding the `clear` keyword and its several options as a property. It would be difficult to find any modern codebase that doesn't use `clear`, especially if `float` is being used. Removing `clear` basically makes `float` unusable, which removes a lot of the power of dynamic page formatting.

I suppose people using elm-css could just write in a custom property for `clear`, but seems to defeat the purpose of the library. The clear keyword seems too fundamental to CSS styling to be omitted.

**Comment by zazaian** [comment]
Also I'm not sure that it would be appropriate to release a library so small that it includes only `clearfix`, as it's pretty insignificant to implement in CSS, but I could imagine this being a part of a larger `css-hacks` library, the purpose of which would be to include a number of cross-browser-compatible hacks that would take care of some of these edge cases where the css gets kind of nasty, but hacks are the only way to be truly cross-browser compliant.

**Comment by dstreet26** [comment]
As a user of this library at v17.0.1, I'm finding the omission of `clear` weird when there's so much other CSS API coverage. 

Also I cannot use flexbox for my use-case of targeting old browsers :(

Oh well, guess I'll find another way to style what I need. 

But why was this ticket closed? What was the resolution?
