### ISSUE TITLE
Quick Question regard elm-css syntax...

### ISSUE THREAD

**Issue by rchrdnsh** [rtfeldman/elm-css#119]
Hola @rtfeldman!

sooooo...

you prefer this:

`padding (px 8)`

to this:

`padding 8px`

?

Just curious as to your thought process and / or any limitations or requirements of elm itself to make the syntax this way? Or maybe you prefer latin based languages? ( The cat that is black vs. The black cat... px 8 vs 8px ;-P )

I'm generally always looking for ways to reduce stuff to type, but I'm sure I'm missing a bunch here in my question :-)

Anyway, thanks

R

**Comment by rtfeldman** [comment]
There's no way to make the latter a function call in Elm. :)

**Comment by rchrdnsh** [comment]
ah, i see, since everything in elm is simply an elm function, and that is the common syntax for elm functions...makes sense...

was no biggie, was just curious, thank you :-)

**Comment by rtfeldman** [comment]
No prob!
