### ISSUE TITLE
Post-1.0.0 keywords

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#12]
These are keywords that don't seem necessary for 1.0.0, but which would be required to completely implement the spec.

- [ ] [`additive-symbols`](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style/additive-symbols)
- [ ] [`border-block-end-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-width)
- [ ] [`border-block-start-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-width)
- [ ] [`border-collapse`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse)
- [ ] [`border-image-slice`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice)
- [ ] [`border-image-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-width)
- [ ] [`border-inline-start-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-width)
- [ ] [`border-inline-end-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-width)
- [ ] [`border-image-source`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-source)
- [ ] [`border-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image)
- [ ] [`border-image-repeat`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-repeat)
- [ ] [`border-image-slice`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice)
- [ ] [`text-emphasis`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis)
- [ ] [`text-emphasis-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color)
- [ ] [`text-emphasis-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-position)
- [ ] [`text-emphasis-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style)
- [ ] [`text-combine-upright`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright)
- [ ] [`text-underline-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position)
- [ ] [`text-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation)
- [ ] Experimental values for [`width`](https://developer.mozilla.org/en-US/docs/Web/CSS/width) and [`height`](https://developer.mozilla.org/en-US/docs/Web/CSS/height): border-box, content-box, max-content, min-content, available, fit-content

**Comment by colvardrm** [comment]
I've been working with elm-css for a couple of days (as a side project alongside my CS degree) and I have implemented the border-collapse property. Would you be interested in a pull request?

**Comment by colvardrm** [comment]
I'd be happy to do a few more if you are interested. Just let me know if there's anything I can do.

**Comment by rtfeldman** [comment]
Yeah, absolutely! We're also missing "float" keywords.

**Comment by rtfeldman** [comment]
I've decided to close all the `missing keywords` issues in favor of letting people make PRs based on what specific things they wish existed.
