### ISSUE TITLE
Error: ReferenceError: Elm is not defined

### ISSUE THREAD

**Issue by alebon** [rtfeldman/elm-css#125]
Can not build examples or new projects. Got this error and no files are generated, installed elm (npm install -g elm and npm install -g elm-css).

examples git:(master) ✗ elm css -module Stylesheets src/Stylesheets.elm
Success! Compiled 0 modules.                                        
Successfully generated /var/folders/2j/9vgg7gfn2952ydks2221cpfr0000gn/T/tmp-52171pz7hIC9JxBuz/emitter.js
Error: ReferenceError: Elm is not defined

**Comment by jwoudenberg** [comment]
I had the same problem, it was fixed with #124 but that change is not yet found in the version on NPM.

As a workaround for now, you can clone the repo, `npm link` it and then use the version of `elm-css` exposed directly by the cloned repo.

**Comment by rtfeldman** [comment]
@alebon @jwoudenberg just published 0.5.0 - let me know if this fixes it?

**Comment by alebon** [comment]
Yes, for me it works now with 0.5.0
