### ISSUE TITLE
Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by jaapz** [rtfeldman/elm-css#127]
After moving to elm 0.17, when I try to compile my stylesheets, I get the error `Cannot set property 'innerHTML' of undefined.

    $ elm css src/Stylesheets.elm
    Success! Compiled 1 module.
    Successfully generated /tmp/tmp-203399vbfNzSjsZyJ/emitter.js
    Error: TypeError: Cannot set property 'innerHTML' of undefined

    $ elm
    Elm Platform 0.17.0 - a way to run all Elm tools

I am using the elm-css version from the master branch as the one on npm is currently broken with elm 0.17.

Is there a way I can debug this further?

**Comment by msdark** [comment]
I was having the same issue, looks like now you need to set an entry point/main function for your `Stylesheets.elm` module like

        port module Stylesheets exposing (..)

    import Css.File exposing (..)
    import Html exposing (div)
    import Html.App as Html

    import HomepageCss as Homepage


    port files : CssFileStructure -> Cmd msg

    cssFiles : CssFileStructure
    cssFiles =
      toFileStructure [ ( "homepage.css", compile Homepage.css ) ]

    main : Program Never
    main =
      Html.program
      { init = ( (), files cssFiles)
      , view = \_ -> (div [] [] )
      , update = \_ _ -> ( (), Cmd.none )
      , subscriptions = \_ -> Sub.none
      }

**Comment by jaapz** [comment]
Interesting. I'll try that... However that smells like a bad API to me, @rtfeldman maybe you can shed some light on the issue?

**Comment by jaapz** [comment]
So I used to do this:

    elm css src/Stylesheets.elm

Which worked for earlier versions.
However with the current version that breaks (as described in the issue).

I do have a `Html.program` which has the cssFiles port in my "Main" program, so I just call:

    elm css src/Main.elm --module=Main

Which does output the correct CSS files.

Still think this is pretty weird though.

**Comment by rtfeldman** [comment]
@jaapz examples have now been updated for 0.17. Does that help? If not, can you post a repo that reproduces this?

**Comment by rtfeldman** [comment]
No response for about a month, so closing...ping me if this is still reproducible!
