### ISSUE TITLE
Psuedo elements are ignored when resolving

### ISSUE THREAD

**Issue by tolgap** [rtfeldman/elm-css#129]
See file: https://github.com/rtfeldman/elm-css/blob/0dff7d3ba870f76b75a0aeebabd84cc813389d9d/src/Css/Preprocess/Resolve.elm#L366

It does include a TODO, but it's also nice to have an issue that we can track.

**Comment by bardt** [comment]
Isn't implementation the same (or very similar) to `ExtendSelector` [case](https://github.com/rtfeldman/elm-css/blob/0dff7d3ba870f76b75a0aeebabd84cc813389d9d/src/Css/Preprocess/Resolve.elm#L278)? Things like `::first-child` work for me, and output should be very similar.

**Comment by tolgap** [comment]
@bardt This is how a `Selector` is defined right now:

```elm
{-| A [CSS3 Selector](https://www.w3.org/TR/css3-selectors/). All selectors
begin with either a type selector or the universal selector, and end with either
zero or one pseudo-elements. In between can be zero or more simple selectors,
separated by combinators.
-}
type Selector
    = Selector SimpleSelectorSequence (List ( SelectorCombinator, SimpleSelectorSequence )) (Maybe PseudoElement)
```

Which is the a sound definition of a selector in my opinion. You can't nest deeper in a pseudo element, but you can in a pseudo class (like `:first-child`).

However, like you said, the logic should mostly be the same, because it needs to be applied to the last `StyleBlock` of a list of declarations. I'm gonna take a stab at this today to see if I can use the `ExtendSelector` logic and modify the `concatMapLastStyleBlock` logic to use a `PseudoElement` instead of a `RepeatableSelector`.

**Comment by bardt** [comment]
Should we close this issue?

**Comment by rtfeldman** [comment]
Yep, thanks!
