### ISSUE TITLE
Error on `port files =`

### ISSUE THREAD

**Issue by ulyssesp** [rtfeldman/elm-css#130]
With Elm 0.17 I'm getting an error in the `Stylesheets` module on `port files =`:

```
I ran into something unexpected when parsing your code!

7| port files =
              ^
I am looking for one of the following things:

    the "has type" symbol ':'
    whitespace

Detected errors in 1 module.                                        
Error: Errored with exit code 1
```

According to the elm architecture tutorial (http://guide.elm-lang.org/interop/javascript.html) it looks like special handling of ports has to be declared separately from the port itself.

**Comment by rtfeldman** [comment]
Hm...do you have `port module` at the very top of the file? Or just `module`?

**Comment by ulyssesp** [comment]
It doesn't work with either of them.

**Comment by rtfeldman** [comment]
@ulyssesp

**Comment by ulyssesp** [comment]
Can confirm that @stoeffel's fixes work.
