### ISSUE TITLE
Overloading and Global Values

### ISSUE THREAD

**Issue by colvardrm** [rtfeldman/elm-css#133]
The current means of allowing a property to accept overloaded values allows it to accept all of the defined overloaded values. It may also prevent these properties from accepting global values, but this could be due to the issue mentioned below. For example, textAlign can be set to "top", even though it should only accept "left" or "right" from the overloaded values. It also won't accept "inherit" or "none"

Additionally, the "inherit" and "none" values don't apply to all properties currently, with borderStyle being an example of this. borderStyle does also accept some overloaded values, specifically those shared with the textDecorationStyle methods, so it could be related to the above issue.

**Comment by rtfeldman** [comment]
Note for later: this is two separate issues.

* `borderStyle` is missing `inherit` and `none` support. Probably others have this problem too.
* We should add a validation (like "rgb values can't be below 0 or above 255") to generate warnings for stuff like `textAlign top`. It doesn't seem realistic to catch this as a type mismatch, considering I don't see a way to have `left` still work for `left: 0` and `top` still work for `top: 0` while having `textAlign left` type-check but `textAlign top` not

**Comment by rtfeldman** [comment]
These have both been fixed!
