### ISSUE TITLE
SVG elements

### ISSUE THREAD

**Issue by architectcodes** [rtfeldman/elm-css#139]
Hey there, first of all warm thanks for creating this amazing tool!

Looking for a workaround for https://github.com/rtfeldman/elm-css-helpers/issues/2, I wanted to reach my `<svg>` through a `Css.children` selector combined with a `Css.Elements.svg`. But it turns out that `Css.Elements` only contains strict HTML elements.

I was wondering – is support for SVG elements on your roadmap?

**Comment by rtfeldman** [comment]
I don't have any concrete plans for SVG elements, but offhand I can't think of why we couldn't support them!

**Comment by Deimos28** [comment]
Hi! Thanks for the work on elm-css! I too would be very interested in styling SVGs!

**Comment by rtfeldman** [comment]
Closing now that we have support for styling SVGs!
