### ISSUE TITLE
`each` with pseudo classes only apply to last selector

### ISSUE THREAD

**Issue by matsrietdijk** [rtfeldman/elm-css#140]
```
each [input, selector "textarea"]
    [ focus
        [ borderColor (hex "#000000")
        ]
    ]
```
Currently results in:
```
input, textarea:focus {
    border-color: #000000;
}
```
Expected was:
```
input:focus, textarea:focus {
    border-color: #000000;
}
```

**Comment by rtfeldman** [comment]
Thanks @matsrietdijk!

This is still reproducible in 4.0.1.

I wrote a failing test to reproduce it on a branch: edf83471b9aaa11c95c86c13f87d1086927bde98 - test output is:

![screen shot 2016-07-22 at 9 56 43 am](https://cloud.githubusercontent.com/assets/1094080/17064681/a0d45c0e-4ff2-11e6-8058-a1a3e8a70cd6.png)

**Comment by rtfeldman** [comment]
Fixed in https://github.com/rtfeldman/elm-css/pull/146 by @tolgap, who is on FIRE with the contributions! 🎆
