### ISSUE TITLE
Border keywords

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#15]
These are keywords necessary to cover Border

- [x] [`border`](https://developer.mozilla.org/en-US/docs/Web/CSS/border)
- [x] [`border-block-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end)
- [x] [`border-block-end-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-color)
- [x] [`border-block-end-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end-style)
- [x] [`border-block-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start)
- [x] [`border-block-start-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-color)
- [x] [`border-block-start-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start-style)
- [x] [`border-bottom`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom)
- [x] [`border-bottom-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-color)
- [x] [`border-bottom-left-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-left-radius)
- [x] [`border-bottom-right-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-right-radius)
- [x] [`border-bottom-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-style)
- [x] [`border-bottom-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-width)
- [x] [`border-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-color)
- [x] [`border-image-outset`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-outset)
- [x] [`border-inline-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end)
- [x] [`border-inline-end-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-color)
- [x] [`border-inline-end-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end-style)
- [x] [`border-inline-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start)
- [x] [`border-inline-start-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-color)
- [x] [`border-inline-start-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start-style)
- [x] [`border-left`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-left)
- [x] [`border-left-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-color)
- [x] [`border-left-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-style)
- [x] [`border-left-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-left-width)
- [x] [`border-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius)
- [x] [`border-right`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-right)
- [x] [`border-right-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-color)
- [x] [`border-right-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-style)
- [x] [`border-right-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-right-width)
- [x] [`border-spacing`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing)
- [x] [`border-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-style)
- [x] [`border-top`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top)
- [x] [`border-top-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-color)
- [x] [`border-top-left-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-left-radius)
- [x] [`border-top-right-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-right-radius)
- [x] [`border-top-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-style)
- [x] [`border-top-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-width)
- [x] [`border-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-width)

**Comment by rtfeldman** [comment]
I'm working on this one. It's in progress!

**Comment by QuinnFreedman** [comment]
does border-spacing exist? I don't see it anywhere
