### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by evancz** [rtfeldman/elm-css#154]
People don't know what this library does. Here are two examples:

  - https://www.reddit.com/r/elm/comments/4wx7i7/wrote_about_my_first_impressions_of_elm/
  - https://groups.google.com/forum/#!topic/elm-dev/f2hvlXieOuc

In one case, the person actually knew about the library, but did not know its full feature set.

If I were to rewrite the readme, I would order it like this:

  - Title
  - Example (the first chunk of code you already have)
  - Features as very short bolded bullets with normal elaboration. Like this:
      - **Generate CSS.** We can make .css files.
      - **Inline styles.** You can just put the styles in directly.
      -  **Refactorable class names.** Classes are given as union types, so any typos or changes are detected by the compiler.
  - Various instructions and further details.

People don't read prose, so it's best to put it later. People who want to read will make it there. Folks who don't are more likely to skim their way into being interested.

**Comment by rtfeldman** [comment]
Thanks for pointing this out! I revised it a bunch. We'll see if it helps.

**Comment by jbucaran** [comment]
Hi @rtfeldman! Thanks for creating elm-css.

Also, please state what needs to be installed, i.e., exactly what commands need to be entered at the command line to get started.
 
For example:

```
elm package install rtfeldman/elm-css -y
```

Also, how's this different from elm-css-helpers. A simple "hello, world" example can always go a long way.
