### ISSUE TITLE
How are fonts supposed to be set?

### ISSUE THREAD

**Issue by SandiDusic** [rtfeldman/elm-css#158]
[This tutorial](https://github.com/rtfeldman/elm-css/blob/5b10188fa0bb221a9b6de1a8b1dba46472a22ef7/Tutorial.md) has the following line of code:
```[ fontFamily [ "Georga", "serif" ]```

But when I try something similar in my code, I get the following error:
```
The argument to function `fontFamily` is causing a mismatch.
Function `fontFamily` is expecting the argument to be:
    { a | fontFamily : Css.Compatible, value : String }
But it is:
    List String
```

The compiler accepts `fontFamily sansSerif` (or serif), but that's not exactly a plethora of choices.

**Comment by tolgap** [comment]
That should be `fontFamilies` (so plural). Will need to fix that example! If you wouldn't mind, you could apply the fix to that example and open a pull request :)

**Comment by SandiDusic** [comment]
Sure, I'll do so tomorrow. Thanks for the clarification!

**Comment by SandiDusic** [comment]
Here: https://github.com/rtfeldman/elm-css/pull/159
