### ISSUE TITLE
Background keywords

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#16]
These are keywords necessary to cover Background

- [ ] [`background`](https://developer.mozilla.org/en-US/docs/Web/CSS/background)
- [ ] [`background-attachment`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment)
- [ ] [`background-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode)
- [ ] [`background-clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip)
- [ ] [`background-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color)
- [ ] [`background-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image)
- [ ] [`background-origin`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin)
- [ ] [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position)
- [ ] [`background-repeat`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat)
- [ ] [`background-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size)

**Comment by jwoudenberg** [comment]
I've got this one!

**Comment by rtfeldman** [comment]
Awesome, thank you! :smile_cat:

**Comment by rtfeldman** [comment]
I've decided to close all the `missing keywords` issues in favor of letting people make PRs based on what specific things they wish existed.
