### ISSUE TITLE
rgba sets { color | alpha = 1 }

### ISSUE THREAD

**Issue by martindemello** [rtfeldman/elm-css#166]
Wasn't sure if this was a bug or there for a reason, but https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L823 always sets alpha to 1 regardless of the input parameter.

**Comment by rtfeldman** [comment]
Defintely intentional! The alternative would be to have `alpha` be a `Maybe`, which doesn't seem like it'd be worth it. 😄 

Thanks for bringing it up though!

**Comment by martindemello** [comment]
i don't get it - `rgb(r, g, b) -> {r, g, b, 1}` makes sense, but `rgba(r, g, b, a)` already validates all four inputs, so why not construct `{r, g, b, a}`?

the current behaviour is inconvenient because i'm trying to write a function to generate svg styles from a Color, and allow that colour to be constructed via `rgba` when calling it.

**Comment by tolgap** [comment]
@rtfeldman I have to repeat @martindemello and say "I don't get it".

Function `rgb` calls `rgba` with alpha value of `1`. That's perfectly fine.

Function `rgba` calculates everything needed, and sets the `{ value }` field correctly, but eventually sets the `{ alpha }` value to `1`, even though you explicitly pass the `alpha` value in the function definition.

**Comment by rtfeldman** [comment]
That would be because I completely misread the OP. 😨

You're totally right! If you want to put in a PR for this, I would gladly accept it.

Really sorry about that!

**Comment by martindemello** [comment]
i guess it didn't help that my attempt to link to the line of source went invalid :) will send in a pr
