### ISSUE TITLE
Proposal: Replace Css.Color with Color.Color

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#167]
## Status Quo

So right now we have functions like these:

```elm
rgb : Int -> Int -> Int -> Css.Color
hex : String -> Css.Color

backgroundColor : Css.ColorValue compatible -> Mixin
```

In principle, we could instead have these use the [Color.Color](http://package.elm-lang.org/packages/elm-lang/core/latest/Color) type from `elm-lang/core`:

```elm
rgb : Int -> Int -> Int -> Color.Color
hex : String -> Color.Color

backgroundColor : Color.Color -> Mixin
```

This would make [color mixing](https://github.com/rtfeldman/elm-css/issues/76) integration really nice.

## Challenges

There are four main challenges here.

1. The CSS [`currentColor`](https://www.w3.org/TR/css3-color/#currentColor-def) value is not representable as a `Color.Color` value
2. This means it's impossible to have `backgroundColor inherit` or `backgroundColor initial`. You'd have to have something like `backgroundColor inheritColor` and `backgroundColor initialColor`, and explain in the docs why that's the case.
3. What if someday there's a CSS property that can accept either a color or `none`? If we go down this road, we can't pass e.g. `rgb 255 255 0` directly to that; instead, we'd have to pass like `notNone (rgb 255 255 0)`. I'm not currently aware of any CSS properties that work like this, but maybe that will change someday.
4. Wanting to faithfully emit exactly the author wrote (e.g. I write `hsl 52 22 76` and I get `hsl(55, 22, 76)` in my stylesheet, instead of getting some `rgba()` value emitted, because that's how `Color.Color` represents them internally and what I originally wrote is not available to the emitter.) A related problem is that we can't give nice warnings, e.g. if you wrote `hex "ff00f"` (invalid because it's 5 hex characters) we can't say `"ff00f" is an invalid hex code` because the compiler can't know that you originally wrote that.)

## Solutions

1. We can set `currentColor = Color.rgb (rem 1 0) (rem 1 0) (rem 1 0)` to make it have `NaN` for all three colors. No matter what arithmetic anyone attempts to do on this, it will still be three `NaN` values at the end of the day. (Granted, if someone's mixing library hardcodes values, that will break this.) The compiler can choose to interpret "three `NaN` values" as an indication that we should emit `currentColor`.

2. The same trick as `currentColor` could work with `initialColor` and `inheritColor` - just use `Infinity` and `-Infinity` instead of `NaN`. This is still undesirable though. Both `inherit` and `initial` would have to have a big note about how you need to use `inheritColor` and `initialColor` with colors.

3. What if someday there's a CSS property that can accept either a color or `none`? Well, then that one property will be inconvenient to use and everything else will be nice. I'm fine with that.

4. There's no getting around this one if color mixing is involved. We could try to get crazy and do things like "store `NaN` in `alpha` and then use the remaining three `Float` values to encode what `String` value the author originally passed to `hex`" - but then if anyone does any color mixing on that along the way, the warning will be actively gibberish. This seems 

## Conclusions

Points 1 and 2 seem fine.

Thinking about the third point more is what's made me okay with this idea. What I realized is that we actually have this problem if we want any kind of third-party color mixing to be available whatsoever. In order for `darken 500 (hex "ff00f")` to preserve the warning message (namely that the original `ff00f` is an invalid hex value), `darken` needs to be aware of the `elm-css` notion of `Color`.

Reducing all this, we have:

Use of third-party color mixing precludes the current warnings style, and also precludes outputting what the author originally inputted.

So if we want this (and it's certainly something people have been asking for), that means:

1. Regardless of what you typed in, you get the same output (e.g. you write `rgb 255 0 0` but it emits `#ff0000`)
2. Invalid color values warn can't know what you typed in. However, what we can do is to present to you the colors in `rgba`, `hsla`, and `hex` format so you can hopefully spot the original (if it was unaltered; if it was altered, you're pretty much out of luck).

## Summary of Proposed Changes

(1) New type signatures for color-related things mean third-party color mixing is trivial:

```elm
rgb : Int -> Int -> Int -> Color.Color
hex : String -> Color.Color

backgroundColor : Color.Color -> Mixin
```

(2) Move `rgb` and `hex` into the `Css.Color` module to avoid namespace collisions with functions in the `Color.Color` module. (Plus that way you know if you aren't importing either that module or `Color`, you must necessarily be sticking to your theme colors, which would be great to be able to verify at a glance.)

(3) `currentColor` becomes defined as `hsla NaN NaN NaN NaN` and the compiler emits `currentColor` if it sees a `Color.Color` with `NaN` in all four floats returned by `Color.toHsla`. (Relatedly, but less importantly, set `transparent = rgba 0 0 0 0` and emit the literal `transparent` whenever we see something with those values. According to the spec, [`transparent` is an alias for that rgba value](https://www.w3.org/TR/css3-color/#transparent) anyway.)

(4) Introduce `initialColor : Color.Color` and `inheritColor : Color.Color` and mention them in the docs for `initial` and `inherit`. They create the colors `rgba Infinity, Infinity, Infinity, Infinity` and `rgba -Infinity, -Infinity, -Infinity, -Infinity`, respectively, but emit `initial` and `inherit`.

(5) Always emit color values in the same format (hex by default, since `#ff0000` is more concise than `rgb(255, 0, 0)` and friendlier to most graphics editing programs), regardless of what the author originally wrote.

(6) When displaying warnings for invalid color values, display the `rgba`, `hsla`, and `hex` values so the user can spot the one they originally wrote.

**Comment by rtfeldman** [comment]
An alternative would be to introduce `clr : Color.Color -> Css.ColorValue compatible` and `toColor : Css.ColorValue compatible -> Color.Color`

This would be less invasive and would make `initial` and `inherit` continue to work as normal. It would also avoid the `currentColor`, `initialColor`, and `inheritColor` hacks.

**Comment by rtfeldman** [comment]
I am currently leaning toward the alternative but open to suggestions. 😄

**Comment by Dremora** [comment]
I was just about to suggest the alternative, but you've saved me from typing a bunch of words :)

One thing, `toColor` might not be able to return `Color.Color` if the value is `initial` or `inherit`.

**Comment by knewter** [comment]
I kind of like `fromColor` more than `clr` but that's bikeshedding.  I like the alternative.  Is anyone willing to write up a few examples of what using mixing looks like in both styles?  I'd do it but react native...is eating my night.

**Comment by rtfeldman** [comment]
I gave it that name just thinking about how it'd feel to use. It's the type of thing you'd write out by hand a lot.

```elm
backgroundColor (rgb 24 24 128)

backgroundColor (clr Theme.primary)

backgroundColor (fromColor Theme.primary)
```

**Comment by pdamoc** [comment]
What would be the disadvantage of just expanding the `Color` tagged union with `Inherit` and `Initial` maybe having `cssValue` that would output a valid CSS value?

**Comment by Dremora** [comment]
`Inherit` and `Initial` are not part of what color actually means and don't apply in contexts outside of CSS (I with they were never part of CSS either, and it's totally possible to avoid them entirely, but that's a separate discussion). For instance, these values wouldn't make any sense when drawing on `<canvas>`.

**Comment by rtfeldman** [comment]
Yeah, also `Color.toRGB : Color -> { r : Int, g : Int, b : Int, a : Float }` can't really work if the internal `Color` isn't an actual color. It would make a lot of mixing stuff more complicated; I don't think that would be worth it.

**Comment by tolgap** [comment]
@pdamoc If one were to change another `Mixin` to use a tagged union to support `Inherit` and `Initial`, the constructors would collide.

```
type ColorValue
    = Value Color.Color
    | Inherit
    | Initial

type ListItemStyle
    = ListItemValue ListItem
    | Inherit
    | Initial
```

Could this be avoided with a different kind of construction without introducing too many tagged unions?
