### ISSUE TITLE
Use with Javascript

### ISSUE THREAD

**Issue by lpil** [rtfeldman/elm-css#181]
Hello!

A silly hair-brained question: Can one use this library with Javascript? I'm looking for an alternative to CSS modules and I rather like Elm :)

Cheers,
Louis

**Comment by eeue56** [comment]
Yep, just compile it to css

**Comment by lpil** [comment]
Sorry, I should have been more clear. I mean there importing of class names feature.

**Comment by ahstro** [comment]
I don't think that it's supported right now, but I don't see why you couldn't write a [webpack loader](https://webpack.js.org/concepts/loaders/) that lets you import classes similar to how you'd import CSS modules. Might be worth checking out [elm-css-webpack-loader](https://github.com/tcoopman/elm-css-webpack-loader) for some inspiration/potential code reuse?
