### ISSUE TITLE
display: table

### ISSUE THREAD

**Issue by butchcom** [rtfeldman/elm-css#183]
I think that there's no support for `display: table` and derivatives (or I'm just not able to find them). I'd really appreciate it, if that could be added.

**Comment by tolgap** [comment]
@butchcom display: table issue is also mentioned here: https://github.com/rtfeldman/elm-css/issues/111

**Comment by butchcom** [comment]
Ok, I didn't notice that issue.

**Comment by rtfeldman** [comment]
@butchcom @tolgap would be happy to accept a PR to add it!
