### ISSUE TITLE
Math functions add spaces between value and unit

### ISSUE THREAD

**Issue by BrianHicks** [rtfeldman/elm-css#184]
Smallest example I can find, but it seems to work with all the units:

```elm
(em 10 |/| em 2).value == "5 em"
```

Chrome treats this as an invalid value because of the space. I'm using Elm 0.17.1 and elm-css 6.1.0.

**Comment by BrianHicks** [comment]
Temporary workaround:

```elm
fixMath : { a | value : String } -> { a | value : String }
fixMath v =
    { v | value = v.value |> String.filter ((/=) ' ') }
```

```elm
(em 10 |/| em 2) |> fixMath |> .value == "5em"
```

**Comment by tolgap** [comment]
The issue comes from [`combineLengths`](https://github.com/rtfeldman/elm-css/blob/6e18342839443edfebed0c2edb7b09075a1666af/src/Css.elm#L1061) where `String.join " "` is used, adding spaces between the length value and length unit.

**Comment by rtfeldman** [comment]
Thanks all! This will be fixed in next release.
