### ISSUE TITLE
z-Index

### ISSUE THREAD

**Issue by amitu** [rtfeldman/elm-css#186]
How to set zIndex CSS property?

**Comment by tolgap** [comment]
Z-index is not in elm-css yet. I use the following function:

```elm
zIndex : Int -> Mixin
zIndex i =
    property "z-index" <| toString i
```

If there is a property not present in elm-css, you can use `property` to define it yourself.

**Comment by amitu** [comment]
@tolgap Thanks :-)

Would be useful to have that bit in README.md (along with how to create a non covered pseudo selector say).

**Comment by tolgap** [comment]
@amitu you're right. Most opened issues or questions on Slack are about missing properties that can be resolved using `property` function.

**Comment by rtfeldman** [comment]
@amitu @tolgap that one is super easy to add if anyone wants to make a PR 😉

**Comment by lukewestby** [comment]
#191

it's been a while so i took a stab at it. it turns out that if we want to cover all the possible values for z-index it's not so simple, but covering just ints is fine

**Comment by rtfeldman** [comment]
Added in https://github.com/rtfeldman/elm-css/pull/195
