### ISSUE TITLE
Discussion: support for "display flex", "justifyContent flexStart" and similar cases

### ISSUE THREAD

**Issue by szubtsovskiy** [rtfeldman/elm-css#198]
Hey guys! 

I think elm-css is a great approach and I would like it to become even better. When I was porting styles in my project to elm-css I discovered that it is impossible to use `flex` as argument to `display` function. For the very same reason it is impossible to implement `justifyContent` the way it would align with everything else. In long term I would like elm-css to avoid having functions like `displayFlex` which look like a quick trade-off to me.

I have done a research in elm-css and realized that, though generally it is not hard to add support for `display flex`, it affects a lot of other stuff like `none` and `auto` functions which are used almost everywhere. There are dozens of functions which accept `none` as argument. Only changing this function would mean that all other functions which fit to the same place where it is accepted would need to change, and so on, and so on...

By writing this I'd like to know if you guys have thought about supporting this kind of stuff and initiate a discussion about the best approach to address this. Is it at all interesting investment time-wise, cost-wise and priority-wise?

**Comment by rtfeldman** [comment]
The only way it would be possible to support `display flex` would be to remove support for [the current `flex` function](http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#flex).

There is only one way in Elm to support type-checked overloaded CSS values (e.g. how `none` must be an acceptable argument to both `display` as well as to `float`, even though `inline` must be an acceptable argument to `display` and not to `float`) and that is to implement them as records.

It is not possible for `flex` to be both a record for `display flex` as well as a function for `flex none`. It has to be one or the other.

Currently it is a function, but I could see an argument that in this case a record might be the better choice...it's likely that people want `display: flex` more often than `flex: none` or `flex: auto` I'd imagine. 🤔

**Comment by jaredklewis** [comment]
Just a random comment, I think that because using `displayFlex` is more common than using the `flex` property, I would support leaving it as is, with `display: flex` having the exceptional `displayFlex` representation.

My thinking: if there is an exception, might as well have it be a commonly used one so it is easy to remember. I have been using React for a while. I never forget `className`, but I think I have to look up `htmlFor` every time because I only use it rarely.

**Comment by rtfeldman** [comment]
Could also rename the current `flex` function to `flex1`. That would be inconsistent, but not crazy.

**Comment by tolgap** [comment]
@rtfeldman if we do that to `flex`, we could do it to every overloaded function at once in 1 breaking API update.

**Comment by szubtsovskiy** [comment]
It seems better to rename it to `flex3` since this property accepts three arguments. It will keep things consistent.

**Comment by rtfeldman** [comment]
That's interesting. I wonder which other functions that would impact, and where it would be annoying...

**Comment by boxofrox** [comment]
If overhauling the API is ever on the table, consider putting the functions in one module (e.g. Css.Property) and the records in another (e.g. Css.Value), then you can have the `flex` function and the `flex` record.

```elm
import Css.Property exposing (..)
import Css.Value exposing (..)

type StyleClass
    = Example

css =
  stylesheet
  [ class Example
    [ display Css.Value.flex
    , Css.Property.flex auto
    ]
  ]
```

**Comment by dustinfarris** [comment]
Also `inlineFlex`

**Comment by k15a** [comment]
How about having `flex` for `flex none` and `flex_` for `display flex_` the same way `Html.Attributes` has `type_` and `main_`. This could change in all places where a keyword is overloaded. To keep it consistent we could have the keyword without the suffix as property name and the keyword with the suffix as value.

**Comment by rtfeldman** [comment]
Closing in favor of discussion on this proposed fix: https://github.com/rtfeldman/elm-css/issues/432
