### ISSUE TITLE
Is it possible to use pseudo classes

### ISSUE THREAD

**Issue by tcoopman** [rtfeldman/elm-css#2]
The title says it all: Is it possible to use pseudo classes? (hover for example)?

**Comment by rtfeldman** [comment]
That's the plan, although haven't added support for them yet. :)

**Comment by rtfeldman** [comment]
This is now possible! https://github.com/rtfeldman/elm-css/blob/a56ee25c19f379ed34e05dfe9ea8516ea14f2df5/src/Css.elm#L1301-L1306
