### ISSUE TITLE
Font keywords

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#20]
These are keywords necessary to cover Font

- [ ] [`@character-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#@character-variant)
- [ ] [`character-variant()`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#character-variant())
- [ ] [`font`](https://developer.mozilla.org/en-US/docs/Web/CSS/font)
- [ ] [`@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face)
- [ ] [`font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family)
- [ ] [`font-feature-settings`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings)
- [ ] [`@font-feature-values`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values)
- [ ] [`font-kerning`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning)
- [ ] [`font-language-override`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-language-override)
- [ ] [`font-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size)
- [ ] [`font-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust)
- [ ] [`font-stretch`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch)
- [ ] [`font-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style)
- [ ] [`font-synthesis`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis)
- [ ] [`font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant)
- [ ] [`font-variant-alternates`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates)
- [ ] [`font-variant-caps`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps)
- [ ] [`font-variant-east-asian`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian)
- [ ] [`font-variant-ligatures`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)
- [ ] [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric)
- [ ] [`font-variant-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position)
- [ ] [`font-weight`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)
- [ ] [`@ornaments`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#@ornaments)
- [ ] [`ornaments()`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#ornaments())
- [ ] [`@styleset`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#@styleset)
- [ ] [`styleset()`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#styleset())
- [ ] [`@stylistic`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#@stylistic)
- [ ] [`stylistic()`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#stylistic())
- [ ] [`@swash`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#@swash)
- [ ] [`swash()`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#swash())

**Comment by lukewestby** [comment]
@rtfeldman i'm gonna look at implementing some of these tonight, but it looks like a few are already in there. do you know which ones? if not i can go through and figure out which are done.

**Comment by rtfeldman** [comment]
I don't know, unfortunately...but the compiler will probably complain right away if there are duplicates!

**Comment by lukewestby** [comment]
sounds good, i'll take a look. thanks!

**Comment by rtfeldman** [comment]
I've decided to close all the `missing keywords` issues in favor of letting people make PRs based on what specific things they wish existed.

**Comment by FranzSkuffka** [comment]
Any updates on this?
