### ISSUE TITLE
hex sets red, green, blue values to 0

### ISSUE THREAD

**Issue by ydschneider** [rtfeldman/elm-css#203]
I just stumbled over this when I tried mixing some colors.
The [`hex`](http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#hex) function currently sets the red, green, and blue values of the resulting [`Color`](http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#Color) to 0. For the sake of clarity, I propose one of the following changes:

1. Change `hex` from `String -> Color` to `String -> ColorValue NonMixable`. This should be easy to implement and makes it obvious that mixing is impossible. If I haven't missed anything, all exposed functions should not be affected by this change as they expect a `ColorValue compatible`.

2. Parse the given `String` and set red, green and blue to the proper values. This requires a more complex implementation, but gives users of elm-css a bit more freedom.

Either way, I think we should ensure that all values of type `Color` can be mixed, and otherwise use `Color NonMixable`. This should also be a step in the right direction for #76.

**Comment by ydschneider** [comment]
I came to realize that [`hsl`](http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#hsl) and [`hsla`](http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#hsla) behave similarly, so I just [gave it a shot](https://github.com/ydschneider/elm-css/tree/core-color).

I decided to go for option 1 just because it was so quick to implement, but I am curious what others think about the topic.

**Comment by rtfeldman** [comment]
I think option 2 is the way to go, and am going to treat this as a bug.

If anyone can contribute `hsl` and `hsla` implementations that convert to RGB under the hood for color mixing purposes, that would be awesome!

**Comment by ydschneider** [comment]
For `hsl`/`hsla`, it should suffice to adjust one function:

```elm
hslaToRgba : String -> List String -> Float -> Float -> Float -> Float -> Color
hslaToRgba value warnings hue saturation lightness alpha =
    let
        {red, green, blue} = Color.toRgb (Color.hsl hue saturation alpha)
    in
        { value = value
        , color = Compatible
        , red = red
        , green = green
        , blue = blue
        , alpha = alpha
        , warnings = warnings
        }
```

This does require `import Color` though.
