### ISSUE TITLE
Nested max/min-width/height media queries

### ISSUE THREAD

**Issue by jaredklewis** [rtfeldman/elm-css#204]
Hello. The tutorial shows how to use nested media queries, such as `withMedia [ print ] [ color (hex "FF0000") ]`, but is it also possible to include the media's size? I would like to do something similar to the code below, which currently doesn't compile:

```
withMedia [ MediaQuery "max-width: 600px" ] [ color (hex "FF0000") ]
```

Of course if it is possible, it would also be great to have something like:

```
withMedia [ queryMaxWidth (px 600) ] [ color (hex "FF0000") ]
```

**Comment by jaredklewis** [comment]
Ok, I've added support for these features (and many others!) in PR #207

**Comment by jaredklewis** [comment]
After some further experimentation, I had another thought. One alternative to using media queries is using the `width` and `height` signals exposed by `Window` to conditionally apply inline styles.

This is not a total replacement of media queries as:

- Elm `Window` does not expose `window.screen` properties like `colorDepth` and `pixelDepth`.

- In order for media features like `grid` or `any-pointer` to work, Elm `Window` would need to expose the results of running `matchMedia` as signals to let Elm code be conditional upon those things.

- For external stylesheets, the typical CSS organization changes a bit. You need to define classes for each supported media arrangement (e.g. `ContainerXs`, `ContainerLg`, etc...) and then conditionally assign the class at runtime. In usual CSS, there is just a single `container` class that responds.

Thoughts anyone? Any Elm veterans out there that have tried sans-media query and used `Window.dimensions` only?

**Comment by jaredklewis** [comment]
Another thought. Some of the more static media features such as `grid`, `any-hover`, `color` and so on could be collected by in JavaScript and then passed in as flags to `programWithFlags, though this might breakdown if the user moves the window to a different monitor or something.

**Comment by globaljake** [comment]
created a simple PR that helps solve this that just exposes a mediaString helper PR #281

**Comment by rtfeldman** [comment]
Closing now that we have a first-class media query API!
