### ISSUE TITLE
Support the `warn` option

### ISSUE THREAD

**Issue by gkubisa** [rtfeldman/elm-css#210]
The `warn` option could just be passed on to `node-elm-compiler` to enable the warnings.

**Comment by eeue56** [comment]
Is there additional context on this?

**Comment by gkubisa** [comment]
Well, I'd like to see the Elm compiler warnings for my Elm stylesheets. It's not hugely important but would be nice to have IMHO.

**Comment by tolgap** [comment]
Aren't you using the classes/styles in your Elm app? Compiling your app with `--warn` should also generate warnings for your stylesheets, because you import them in your app.

**Comment by rtfeldman** [comment]
Closing in favor of #327
