### ISSUE TITLE
User-Select not supported

### ISSUE THREAD

**Issue by alpox** [rtfeldman/elm-css#220]
There seems to be no css declarator for user-select. I'm not sure if this is intended or was overseen because of the amount of css attributes out there :smile:.
Its still experimental though: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by rtfeldman** [comment]
Thanks! Not an oversight, just not including experimental properties. 😄 

You can always use e.g. `Css.property "user-select" "contain"` in the meantime!

http://package.elm-lang.org/packages/rtfeldman/elm-css/7.0.0/Css#property
