### ISSUE TITLE
BorderCollapse attributes not exposed

### ISSUE THREAD

**Issue by alpox** [rtfeldman/elm-css#221]
As the title describes, all BorderCollapse attributes are not exposed from Css.elm:
https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L2126
And therefore not accessible. (These are `separate` and `collapse`)

**Comment by chaughawout** [comment]
I've fixed this locally but having issues with mocha and the test scripts. A pull request will be on its way if I can get that resolved.

**Comment by eeue56** [comment]
@chaughawout Just open a PR. Travis will handle running the tests properly.

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/elm-css/pull/222
