### ISSUE TITLE
Custom operator for selector chaining

### ISSUE THREAD

**Issue by jwoudenberg** [rtfeldman/elm-css#226]
I'm currently setting up an input checkbox with a custom style. Because styling the input directly is not possible, the general wisdom is that you hide the input itself and then style the label for it. To get the label style to depend on the input item, you can use the `:checked` pseudo selector. Using elm-css, a rule for this state-depending style looks something like this.

```elm
snippets =
    [ input
        [ checked
            [ adjacentSiblings
                [ label
                    [ before
                        [ <custom input styles go here>
                        ]
                    ]
                ]
            ]
        ]
    ]
```

Would it be an idea to add an infix function for composing selectors like this together? Let's say it's `<>` then the above would be reduced to this:

```elm
snippets =
    [ input <> checked <> adjacentSiblings <> label <> before
        [ <custom input styles go here>
        ]
    ]
```

Implementation of `<>` would be:

```elm
(<>) : (List a -> b) -> a -> b
(<>) a b =
    a [ b ]
infixr 0 <>
```

Or perhaps there's a much simpler solution I'm completely missing to see here :).

**Comment by rtfeldman** [comment]
How about an alternative to [`each`](http://package.elm-lang.org/packages/rtfeldman/elm-css/8.1.0/Css#each) called `combine`, which has the same type signature but nests the selectors instead of joining them with `,` like `each` does?

In other words:

```elm
snippetsViaCombine : List Snippet
snippetsViaCombine =
    combine [ input, checked, adjacentSiblings, label, before ] [ display block ]
```

...is the same as:

```elm
snippetsByHand : List Snippet
snippetsByHand =
    [ input
        [ checked
            [ adjacentSiblings
                [ label
                    [ before
                        []
                    ]
                ]
            ]
        ]
    ]
```

**Comment by stoeffel** [comment]
Since we just removed `(.)` and `(#)` I feel it would be better to add `nest` instead of a new operator.

**Comment by jwoudenberg** [comment]
I agree, that looks even better! I'll create a PR.

**Comment by jwoudenberg** [comment]
I spoke to soon, I don't think `nest` is going to work. The problem is that the selectors in the example have different types:

```elm
input : List Mixin -> Snippet
checked : List Mixin -> Mixin
adjacentSiblings: List Snippet -> Mixin
label : List Mixin -> Snippet
before : List Mixin -> Mixin
```

If you try to put them together in a list the compiler won't stand for it. This actually makes a lot of sense: not all combinations of (pseudo)selectors are legal.

Another smaller problem is that the behaviour of calling `nest` with an empty list is undefined.

The `<>` operator doesn't have this problem, because it's only concerned with composing two selectors. It's generic type signature only enforces the thing on the left gets a list of the thing on the right. If you go through the list of type signatures from the bottom upwards, you can see it works out.

I completely understand the hesitance in adding custom infix operators. They're hardy self-documenting and libraries relying on them easily result in symbol soup. That said, this does seem like a particularly valid use-case for one.

**Comment by rtfeldman** [comment]
Ah, yep! Good point.

I tried doing something like what `decode-pipeline` does, but it doesn't look great:

```elm
snippets : Snippet
snippets =
    startChain input
        |> chain checked
        |> chain adjacentSiblings
        |> chain label
        |> chain
            (before
                [ display block
                , left auto
                ]
            )
```

Something else to consider: because you have to invoke the last function in the chain, `elm-format` will format the `<>` code like this:

```elm
snippets : Snippet
snippets =
    input
        <> checked
        <> adjacentSiblings
        <> label
        <> before
            [ display block
            , left auto
            ]
```

Assuming infix operator is the way to go here, I'm not sure if `<>` is best. Feels like something that starts with `|` would be better, but I tried a few options there and wasn't thrilled with any of them. 🤔

**Comment by jwoudenberg** [comment]
Yeah, I think a chain would be a nice alternative if you didn't have to explicitly start and end it, but we need the low specificity at the end to make it work.

The choice for `<>` was pretty random on my part. What about `|::`, which evokes the cons operator and the css pseudo element separator, both of which sort of apply here?

**Comment by jwoudenberg** [comment]
Another possibility using an ordinary functions. Also doesn't look great:

```elm
snippets : List Snippet
snippets =
    [ input <|
        with checked <|
            with adjacentSiblings <|
                with label <|
                    with before
                        [ display none
                        ]
    ]
```

**Comment by stoeffel** [comment]
> I spoke to soon, I don't think nest is going to work. The problem is that the selectors in the example have different types

I might miss something, but that also wouldn't work with `|::` or an other operator, right? we would need different operators for the different types.

**Comment by jwoudenberg** [comment]
Nope, the single operator definitely works (I tested it against the example in this thread). The reason it does is because of it's generic type signature: `(|::) : (List a -> b) -> a -> b`. So whether `a` or `b` in the above is a `Mixin` or a `Snippet`, it works as long as the selectors on both sides compose. For instance: `label` returns a `Snippet` and `adjacentSiblings` takes a `List Snippet`, so `adjacentSiblings |:: label` is valid.

**Comment by stoeffel** [comment]
duh. you're right. I would prefer `|::` over `<>`.

**Comment by jwoudenberg** [comment]
We concluded that because in general it's best to write selectors as non-specific as general, valid use cases of this selector are pretty rare. Closing this issue.
