### ISSUE TITLE
`kabob-case` rather than `PascalCase` class names?

### ISSUE THREAD

**Issue by justgage** [rtfeldman/elm-css#240]
I like using option types for class names however I find it a bit out of the norm for css names when they are generated (most css is `kabob-case`) is there a way to configure that for using in non-elm projects?

**Comment by rtfeldman** [comment]
I'd rather leave the default as-is (principle of least astonishment and all that) - but you could add a stylesheet transformation to implement this, similar to [how `namespace` works](https://github.com/rtfeldman/elm-css/blob/master/src/Css/Namespace.elm#L15-L17).

**Comment by justgage** [comment]
Sounds good, if it becomes a problem I'll consider it.
