### ISSUE TITLE
Is there a way to use named colors?

### ISSUE THREAD

**Issue by radix** [rtfeldman/elm-css#241]
I have a string, like "blue", and I want to set my background-color to that value. I can't figure out a way to do that.

**Comment by dustinfarris** [comment]
@radix you can use [`property`](http://package.elm-lang.org/packages/rtfeldman/elm-css/8.1.0/Css#property) when elm-css doesn't support what you're trying to do.  In this case, backgroundColor wants a type checked value, not a string, but you could instead:

```elm
[ MyClass
    [ property [ "background-color", "blue" ] ]
]
```

**Comment by radix** [comment]
cool, thanks @dustinfarris :)
