### ISSUE TITLE
Missing "none" for "text-transform"

### ISSUE THREAD

**Issue by listrophy** [rtfeldman/elm-css#244]
`none` is a supported value per the [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform), but is not supported by elm-css.

## Expected Usage

    div [ textTransform none ]

**Comment by rtfeldman** [comment]
Anyone want to take a stab at this? It's a pretty easy first contribution; the change should look very similar to https://github.com/rtfeldman/elm-css/pull/236

**Comment by BobWhitelock** [comment]
I can take a look at this, I should be able to later today.
