### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by k15a** [rtfeldman/elm-css#257]
Hey,

I thought that elm-css needs a logo so I created a sketch. Hopefully you like it^^

![elm-css](https://cloud.githubusercontent.com/assets/20357450/25313128/b7482290-2828-11e7-8ec7-741cdaaf06c9.png)

**Comment by rtfeldman** [comment]
😻 😻 😻 😻 😻 

Do you want to make a PR to add it to the top of the README?

**Comment by rtfeldman** [comment]
Added in https://github.com/rtfeldman/elm-css/pull/258
