### ISSUE TITLE
[Quick fix!] Typo in repository description

### ISSUE THREAD

**Issue by ialexryan** [rtfeldman/elm-css#262]
The current repo description reads "...where you can share code **between between** your stylesheets and..." (emphasis mine).

**Comment by dustinfarris** [comment]
If you click the edit button [on the README](https://github.com/rtfeldman/elm-css/blob/master/README.md) you can actually make this change yourself so the owner just has to accept your pull request.

![screenshot 2017-05-04 14 24 11](https://cloud.githubusercontent.com/assets/1087165/25718805/7155310a-30d5-11e7-8c79-6805ac039697.png)

**Comment by ialexryan** [comment]
The error is in the **_repository description_** like I said, not the readme.

![image](https://cloud.githubusercontent.com/assets/2292782/25785691/dd0b89a4-333b-11e7-959e-296ce5fb14a6.png)

@rtfeldman super quick fix?

**Comment by rtfeldman** [comment]
Super quickly fixed! Thanks for the clarification @ialexryan 😄

**Comment by ialexryan** [comment]
My pleasure! Thanks for indulging my OCD and making (and sharing) this awesome library.
