### ISSUE TITLE
Add a way to set additional conditions on selectors

### ISSUE THREAD

**Issue by arowM** [rtfeldman/elm-css#266]
The sample CSS bellow is not a rare case, I guess.

```
#foo[aria-disabled='true'] {
  background-color: gray;
}

#foo[aria-busy='true'] {
  cursor: default;
}

#foo[aria-hidden='true'] {
  display: none;
}
```

Would it be a good idea to provide `with : List Snippet -> Mixin`?
If we have it, we can express above sample in elegant `elm-css` code.

```
id "foo"
  [ with
    [ selector "[aria-disabled='true']"
      [ backgroundColor gray
      ]
    , selector "[aria-busy='true']"
      [ cursor default
      ]
    , selector "[aria-hidden='true']"
      [ display none
      ]
    ]
  ]
```

Or am I missing some simpler solution?

**Comment by Lattyware** [comment]
The thing that jumps out is that this would create a situation where you can do:

id "foo"
  [ with
    [ id "bar"
      []
    ]
  ]

Which compiles down to `#foo#bar {}` which doesn't make any sense given an item can only have one ID. That said, as far as I can tell it would just be a rule that can never match, not actually invalid css, as id selectors are directly equivalent to `[id=foo]` attribute selectors according to the spec, and there are no limits on the number of attribute selectors you can have.

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/rtfeldman/elm-css/issues/433 for attribute selectors!
