### ISSUE TITLE
Add support for missing elements.

### ISSUE THREAD

**Issue by akoppela** [rtfeldman/elm-css#271]
There are some elements missing. e.g. `q`, `aside`, `time`, `menu`, etc... 
It will be good to expose `typeSelector` from `Css.Elements` module. So it will be more easy at the moment to have missing elements. In the similar way it's possible to have missing properties by using `property`.

**Comment by tolgap** [comment]
We now have a way of defining missing selectors in our own applications, using `typeSelector` 🎉 . Can we close this issue?

**Comment by akoppela** [comment]
Thank you very much!
