### ISSUE TITLE
--module doesn't work if there are dots in the module name

### ISSUE THREAD

**Issue by avh4** [rtfeldman/elm-css#278]
If my stylesheet module is `port module NriStyles`, then this works:  `elm-css src/Nri/Styles.elm --module NriStyles`

But if I change to `port module Nri.Styles`, then I get this error:

```
$ elm-css src/Nri/Styles.elm --module Nri.Styles
Error: I couldn't find the entry module Nri.Styles.

Maybe you meant: Nri
You can pass me a different module to use with --module=<moduleName>

$ elm-css src/Nri/Styles.elm --module Nri
Error: TypeError: Elm[stylesheetsModule].worker is not a function
```

**Comment by eeue56** [comment]
Initially looks like it _should_ work: https://github.com/rtfeldman/elm-css/blob/master/index.js#L181

**Comment by BobWhitelock** [comment]
I created a fresh project with a stylesheets module in `src/Nri/Styles.elm` called `Nri.Styles`, and I can confirm that the CSS was generated correctly when I ran `elm-css src/Nri/Styles.elm --module=Nri.Styles`.

Are you using the latest `elm-css`? Looks like support for this was added not that long ago: https://github.com/rtfeldman/elm-css/pull/225.

**Comment by rtfeldman** [comment]
Closing in favor of #327
