### ISSUE TITLE
Unsupported "whiteSpace normal"

### ISSUE THREAD

**Issue by happypoulp** [rtfeldman/elm-css#285]
Hi,

It looks like `whiteSpace normal` is not supported.

When using it, the compiler is giving me this error:

```
The argument to function `whiteSpace` is causing a mismatch.

84|               whiteSpace normal
                             ^^^^^^
Function `whiteSpace` is expecting the argument to be:

    Css.WhiteSpace compatible

But it is:

    Css.Wrap (Css.FontStyleOrFeatureTagValue (Css.FontWeight {}))

Hint: The record fields do not match up. One has whiteSpace. The other has
featureTagValue, fontStyle, fontWeight, overflowWrap, and warnings.
```

### Reproduced on environment:
- elm-version: "0.18.0 <= v < 0.19.0"
- rtfeldman/elm-css: "8.2.0 <= v < 9.0.0"

Thanks.

**Comment by BobWhitelock** [comment]
Looks like we don't support most (all?) of the other properties in [the spec](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) too, I'll take a look at it :slightly_smiling_face:

**Comment by happypoulp** [comment]
Thanks!
