### ISSUE TITLE
Some types mentioned in public type signatures are not exposed

### ISSUE THREAD

**Issue by SelectricSimian** [rtfeldman/elm-css#289]
The following types appear in public type signatures in the `Css` module but are not themselves publicly exposed, making it impossible for other code to use them in explicit type annotations:

- `AlignItems`
- `All`
- `Angle`
- `AngleOrDirection`
- `BackgroundAttachment`
- `BackgroundBlendMode`
- `BackgroundClip`
- `BackgroundImage`
- `BackgroundOrigin`
- `BackgroundRepeat`
- `BackgroundRepeatShorthand`
- `BasicProperty`
- `BorderCollapse`
- `BorderStyle`
- `BoxSizing`
- `Calc`
- `CalcExpression`
- `Cursor`
- `Directionality`
- `Display`
- `ExplicitLength`
- `FeatureTagValue`
- `FlexBasis`
- `FlexDirection`
- `FlexDirectionOrWrap`
- `FlexWrap`
- `FontFamily`
- `FontStyle`
- `FontStyleOrFeatureTagValue`
- `FontVariant`
- `FontVariantCaps`
- `FontVariantLigatures`
- `FontVariantNumeric`
- `FontWeight`
- `ImportType`
- `IncompatibleUnits`
- `JustifyContent`
- `LengthOrAuto`
- `LengthOrAutoOrCoverOrContain`
- `LengthOrAutoOrNoneOrContent`
- `LengthOrMinMaxDimension`
- `LengthOrNoneOrMinMaxDimension`
- `LengthOrNumber`
- `LengthOrNumberOrAutoOrNoneOrContent`
- `ListStyle`
- `ListStylePosition`
- `ListStyleType`
- `MinMaxDimension`
- `None`
- `NonMixable`
- `Number`
- `Outline`
- `Overflow`
- `Position`
- `Resize`
- `TextDecorationLine`
- `TextDecorationStyle`
- `TextIndent`
- `TextOrientation`
- `TextOverflow`
- `TextRendering`
- `TextTransform`
- `TouchAction`
- `Transform`
- `TransformBox`
- `TransformStyle`
- `Value`
- `VerticalAlign`
- `WhiteSpace`
- `Wrap`

Exposing these types would not affect the fundamental type safety of `elm-css`, since these types are all already publicly accessible through type inference; they simply cannot be explicitly named.

**Comment by bobwhitelock** [comment]
This change sounds reasonable to me, unless there's some reason I'm missing why we don't want to do this.

If we do want to expose these then I've added a PR to do this; note that the `LengthOrAutoOrNoneOrContent` type mentioned doesn't appear to exist, and `LengthOrNone` seems to meet the criteria to be exposed too. There may be other types which should also be exposed, but I've not looked for these in depth.

I'll also be interested to see what the outcome of your [compiler issue](https://github.com/elm-lang/elm-compiler/issues/1611) related to this is. :slightly_smiling_face:

**Comment by SelectricSimian** [comment]
You're right about `LengthOrAutoOrNoneOrContent` -- the actual type is `LengthOrNumberOrAutoOrNoneOrContent`. `LengthOrNone` is also a good catch. Thanks!
