### ISSUE TITLE
Adding in ` \x2028t` results in a compiler error!

### ISSUE THREAD

**Issue by brookeangel** [rtfeldman/elm-css#292]
Adding ` \x2028t` in a string somewhere in elm code causes elm-css to generate this error: 

```
Success! Compiled 0 modules.
elm-css : Successfully generated /var/folders/fj/6f42q6zd287g1rgdfdj5j8q40000gn/T/tmp-25045Lsw8kARH40LC/emitter.js
elm-css : Error: SyntaxError: Invalid or unexpected token
```

(Context: 
`Html.text "Unit diagnostics pre-test student knowledge at the start of a unit. You can later compare results \x2028to those of a growth quiz! "`
)

**Comment by rtfeldman** [comment]
I think this is probably an `elm-make` issue if anything...can you
reproduce in a basic Ellie?

**Comment by eeue56** [comment]
See this: https://github.com/elm-lang/elm-compiler/issues/1279#issuecomment-267800315. Not an elm-css issue
