### ISSUE TITLE
textJustify compiles to "text-justify" instead of "justify"

### ISSUE THREAD

**Issue by Stijnkool** [rtfeldman/elm-css#293]
Source code:
```
textJustify : TextAlign a b
textJustify =
    prop1 "text-justify"
```

Why is the property called `textJustify` and not just `justify`?
And the value that it compiles into, `text-justify` doesn't seem to be valid css.

Can the original piece of code become:
```
justify : TextAlign a b
justify =
    prop1 "justify"
```

**Comment by bobwhitelock** [comment]
I think you're right, it looks like it may have been mixed up with the [text-justify](https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify) property (which we don't currently support). I'll correct it.
