### ISSUE TITLE
Expose a function composing asPairs and Html.Attribute.style

### ISSUE THREAD

**Issue by therealnicksaunders** [rtfeldman/elm-css#296]
This is how we create a function _styles_ to add inline styles to an element per the docs:

```
import Html.Attributes exposing (style)
import Css

styles : List Css.String -> Html.Attribute msg
styles = Css.asPairs >> style
```
It seems to me that it would be good to have this out of the box. Is it already there, and I just overlooked it in the docs?

**Comment by tolgap** [comment]
This would require us to pull in `elm-lang/html` as a dependency, which it isn't right now.

You could add that function to your stylesheet once and import wherever necessary. Otherwise it's a pretty big price to pay for such a small function 🙂.

**Comment by therealnicksaunders** [comment]
@tolgap I really appreciate your answer, and of course avoiding a new dependency is a reasonable argument. However, ```elm package install``` already pulls in ```elm-lang/html``` along with ```elm-lang/core```, so I'm not sure I can imagine a scenario where the client doesn't already have this dependency. Furthermore, the "inline styles" use case (the _first_ approach described in the readme) absolutely requires this function, so the client is faced with repeating this function in all his views (probably a bad practice) or creating his own module along the lines of "CssUtils" to share throughout the app (still resulting in additional imports, project structure considerations, maintenance, et cetera).

If we feel dirty about having an explicit dependency on ```elm-lang/html```, then perhaps someone should publish another module like ```elm-css-html``` (which would of course depend on ```elm-lang/html``` and ```elm-css```) that exposes this function (and perhaps other utilities supporting this use case in the future). What would you think about this option?

Thanks again for your response.

**Comment by tolgap** [comment]
@therealnicksaunders The helpers to use `elm-css` in conjunction with `elm-lang/html` lives in [elm-css-helpers](https://github.com/rtfeldman/elm-css-helpers). So yeah, something for this already exists 😄 . So a function like this could exists there.

**Comment by rtfeldman** [comment]
I'm actually planning to deprecate `asPairs` https://github.com/rtfeldman/elm-css/issues/302

@therealnicksaunders - if you think I shouldn't, would you mind adding your thoughts to that issue in a comment?
