### ISSUE TITLE
Recommendation for using bootstrap 

### ISSUE THREAD

**Issue by meherranjan** [rtfeldman/elm-css#299]
Hi @rtfeldman, great work with the elm-css and I am using this extensively on my current project. Currently I am using bootstrap but because those properties aren't passed through elm-css, the safety switch is under utilised. According to you what is the recommended strategy for using bootstrap alongside elm-css?

**Comment by rtfeldman** [comment]
I think this is more of a question for the `elm-bootstrap` folks. 😄

I don't think `elm-css` should be coupled to Bootstrap in any way, so really it's a question of whether anyone wants to undertake the project of porting Bootstrap's CSS to `elm-css`!
