### ISSUE TITLE
CLI Revamp

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#303]
I'm planning to revamp the CLI experience! I talked all this over with @evancz and came up with a design I'm very excited about.

## Goals

1. Make it so that classnames can be automatically generated at build time, with no runtime cost. (I talked about the motivation for this in [Long Term Goals](https://github.com/rtfeldman/elm-css/wiki/Long-Term-Goals)). Basically what [CSS Modules](https://github.com/css-modules/css-modules) does.
2. No longer require specifying `main` inside a module which has to `import` and aggregate all the styles by hand. Instead, let the CLI discover them (similar to how `elm-test` does now) by traversing files and inspecting exposed values.
3. Embrace that compiling to `.css` files is for advanced users who have performance, asset size, or stylesheet transformation (e.g. autoprefixing) needs that justify doing it this way instead of compiling to `<style>`. The `<style>` approach should be the default for people new to the library because it's easier to set up, builds faster, and supports dynamically changing styles based on the current `model` state.

## Design

1. Put all your `elm-css` files in their own source directory, e.g. `css/`.
2. Put an `elm-package.json` in this `css/` directory (similarly to how you would with tests) which includes only `rtfeldman/elm-css` and any helper packages you want to use to help you build your stylesheets (e.g. for color mixing).
3. Don't include this `css/` directory in your application's `source-directories`, and don't include `rtfeldman/elm-css` in your application's `elm-package.json`. (If we're compiling to `.css` files, there should be no additional runtime cost whatsoever for using them!)
4. Put some modules in this `css/` directory. These modules will determine what goes in the `.css` file.
5. Any exposed values of type `Css.Snippet` in these modules will get compiled to the appropriate output in the `.css` file, just like they do today.
6. Any exposed values of type [`Css.Class`](http://package.elm-lang.org/packages/rtfeldman/hashed-class/1.0.0/Css-Class) (this type will move from `rtfeldman/hashed-class` into `rtfeldman/elm-css`) will get turned into `class` declarations in the `.css` build, and the classname for these classes will be generated at build time. **Additionally,** we will generate a `.elm` file in `elm-stuff/generated-code/rtfeldman/elm-css`, and this `.elm` file is a module which exposes the classname as a `Html.Attributes.class` attribute. See the example below.

## Example

Directory structure:

```
elm-package.json (source-directories: ["src/", "elm-stuff/generated-code/rtfeldman/elm-css"], dependencies: ["elm-lang/html"])

src/
  Dreamwriter/
    Editor.elm
    Sidebar.elm

css/
  elm-package.json  (source-directories: ["."], dependencies: ["rtfeldman/elm-css"])
  Dreamwriter/
    Editor.elm
    Sidebar.elm
```

The contents of `css/Dreamwriter/Sidebar.elm` would be:

```elm
module Sidebar exposing (menu, chapters)


import Css exposing (..)
import Css.Class as Gen


menu : Snippet
menu =
    button [ color "purple", textDecoration none ]


chapter : Class
chapter =
    Gen.class [ color (hex "eeeeee"), backgroundColor "purple" ]
```

I'd run `elm-css --output=build/` and here's what I'd get:

```
elm-package.json (source-directories: ["src/", "elm-stuff/generated-code/rtfeldman/elm-css"], dependencies: ["elm-lang/html"])

build/
  Dreamwriter/
    Editor.css   <--- filenames match the modules in css/ that generated them.
    Sidebar.css

elm-stuff/
  generated-code/
    rtfeldman/
      elm-css/
        Dreamwriter/
          Editor/
            Css.elm   <--- generated by the CLI, never checked in
          Sidebar/
            Css.elm

src/
  Dreamwriter/
    Editor.elm
    Sidebar.elm

css/
  elm-package.json  (source-directories: ["."], dependencies: ["rtfeldman/elm-css"])
  Dreamwriter/
    Editor.elm
    Sidebar.elm
```

Here's what the generated `build/Dreamwriter/Sidebar.css` looks like:

```css
button {
  color: purple;
  text-decoration: none;
}

.Dreamwriter-Sidebar-chapter {
  color: #eeeeee;
  background-color: purple;
}
```

Here's what the generated `elm-stuff/generated-code/rtfeldman/elm-css/Dreamwriter/Sidebar/Css.elm` looks like:

```elm
module Dreamwiter.Sidebar.Css exposing (chapter)

import Html exposing (Attribute)
import Html.Attributes exposing (class)


chapter : Attribute msg
chapter =
    class "Dreamwriter-Sidebar-chapter"
```

You'd never check this file into source control, but you'd be able to use it as normal because `elm-stuff/generated-code/rtfeldman/elm-css` is in your `source-directories`.

Now in your application code, you can do this:

```elm
module Dreamwriter.Sidebar exposing (view)

import Dreamwriter.Sidebar.Css as Style

viewChapter : Chapter -> Html msg
viewChapter chapter =
    li [ Style.chapter ] [ text chapter.title ]
```

## Summary

* Classnames are generated at build time, and exposed in a trivial generated `.elm` file which only exposes `Attribute msg` values.
* The application never depends on `elm-css` or includes the code for the stylesheets in its `source-directories`, so literally all it ever adds to the runtime cost are the string literals for the classnames. (We can also offer a CLI flag like `--minify` to compress the classnames down to like `a`, `b`, etc. Should be super easy to implement.)
* No need to import styles by hand. You add the module in the `css/` directory and you're done. The appropriate things will get generated.
* There's a natural place for CSS helper dependencies (color mixers, etc.) to live: `css/elm-package.json`. It's no longer easy to accidentally introduce dependencies to the application that are only actually needed for building `.css` files.

**Comment by ibizaman** [comment]
There's no mention of handling `#id` tags in the same way that `.class`. Is there a particular reason?

**Comment by dustinfarris** [comment]
I am currently using [dustinfarris/broccoli-elm-css](https://github.com/dustinfarris/broccoli-elm-css) to automate compiling css files and (in conjunction with [broccoli-elm-make](https://github.com/dustinfarris/broccoli-elm-make)) have the output hot-reloaded in the browser as i develop.

I rely on the exported function in index.js to do this.  It would be nice if some kind of non-cli API is preserved.

**Comment by rtfeldman** [comment]
@ibizaman I'm not really aware of demand for auto-generated IDs, and I'd rather default to keeping the API smaller unless I have a compelling reason to expand it. 😄 

@dustinfarris I can have the `npm` package expose that in JS for JS plugin authors; would that work?

**Comment by dustinfarris** [comment]
@rtfeldman yes that would be great 👍

**Comment by sporto** [comment]
Interesting. One thing that I'm not fond about is the `css` directory. Having to maintain a parallel tree of application there is not very appealing. Could you have `Editor.elm` and `EditorCss.elm` in the same src dir?

**Comment by stoeffel** [comment]
How would this work with elm-html-test? We often use the namespaced class for testing.

i.e.
```elm
                View.view model
                    |> Query.fromHtml
                    |> Query.findAll [ class "Page-Learn-Foo-Bar-Moo-View" ]
                   -- ....
```

**Comment by rtfeldman** [comment]
@stoeffel Use [`attribute`](http://package.elm-lang.org/packages/eeue56/elm-html-test/5.1.0/Test-Html-Selector#attribute) instead of `class`:

```elm
Dreamwiter.Sidebar.viewChapter chapter
    |> Query.fromHtml
    |> Query.findAll [ attribute Dreamwiter.Sidebar.Css.chapter ]
```

It's actually more robust because there's no chance of the strings getting out of sync! 😄

**Comment by rtfeldman** [comment]
> Could you have Editor.elm and EditorCss.elm in the same src dir?

@sporto I think that would get confusing. The stylesheets will be relying on a different `elm-package.json` (which is important, in order to avoid `elm-css` assets accidentally getting bundled into production when you're trying to minimize asset size by compiling to a separate `.css` file) so you'd end up with some modules in `src` relying on one `elm-package.json` and some relying on a completely different one!

It might be easy to tell which is which by the ones that end in `_____Css.elm` but it gets trickier if they start needing to share code.

I think in general life will be easier if all the modules in `src/` use the application's `elm-package.json` that gets included at runtime, and `css/` contains modules that use the `elm-package.json` (which is only used at build time).

**Comment by eeue56** [comment]
I have a use case where I want to pass in a flag to say what colors and theme should be generated by elm-css. It would be nice to have support for that.

**Comment by egauderman** [comment]
> - Classnames are generated at build time, and exposed in a trivial generated .elm file which only exposes Attribute msg values.
> - The application never depends on elm-css or includes the code for the stylesheets in its source-directories, so literally all it ever adds to the runtime cost are the string literals for the classnames.

@rtfeldman Under the new system, are `Attribute msg` values literally the only thing that the app can import from the CSS directory?  Will it be impossible to import other values?  For instance, when animating some length from one value to another using app code (like using the "elm-style-animation" library), it would be useful to have access to values that are present in CSS.

**Comment by anagrius** [comment]
@sporto @rtfeldman Not a big fan of the separate folder for css either. While I understand the technical benefits of having a separate project for css, I think it would be a step backwards. Just having to look one place is a big deal code understandability and maintainability.

At Humio we even take it a step further than having `Foo.elm` and `FooCss.Elm` and include a function `css` in every Page and View module. I see the styling as a first class citizen (Just as much as `update` or `view`) and tightly coupled with the `view` functions and animations we perform in code. 

Surely we could do some tree shaking get avoid the runtime inclusion. Of course having css in the same file does not work well with generated class names.

**Comment by rtfeldman** [comment]
> Under the new system, are `Attribute msg` values literally the only thing that the app can import from the CSS directory?  Will it be impossible to import other values? 

@egauderman Nope! You can use `source-directories` both on the root project's `elm-package.json` and on `css/`elm-package.json to let them share as much code as you like. 😄

**Comment by rtfeldman** [comment]
> I see the styling as a first class citizen (Just as much as `update` or `view`) and tightly coupled with the view functions and animations we perform in code.

@anagrius I totally hear you.

Since it sounds like you're okay with a runtime dependency (especially with tree shaking), putting your feedback and @sporto's together, it sounds like both of you would prefer to use a system where you could define reusable styles on a per-element basis at runtime, and that having a separate `.css` file is non-essential; rather, what's essential is that you can use things like `hover` and media queries.

If we had a system that made it nice to do these things at runtime (without a separate compilation step involving the `elm-css` CLI), would that meet your needs?

**Comment by anagrius** [comment]
@rtfeldman hard to say, would love to give it a look-over, to better understand what you are getting at.

**Comment by sporto** [comment]
My feedback was more about the folder structure. I'm hoping that there is a way to avoid the `css` folder and have all the other nice things.

re compiled .css. This will be desirable, but non-essential for us. As long as we can have media queries pseudo elements and hovers we are happy. Injecting styles at run time might not be ideal, but  we are ok with this.

**Comment by anagrius** [comment]
@sporto ditto :)

**Comment by rtfeldman** [comment]
@sporto @anagrius here's the draft documentation I've been working on - thoughts? https://gist.github.com/rtfeldman/7665f28270352521163f9ec2ee772ec1

**Comment by rtfeldman** [comment]
@anagrius and @sporto - I'm also considering a possible design where:

* Compiling to `.css` files is The One Way To Do It
* I publish a separate package of helper functions for values that often change at runtime when animating (e.g. `opacity : Float -> Attribute msg` and `top : Length -> Attribute msg`), since this is the only case where doing things at runtime is mandatory.

Things that appeal to me about this:

1. There is One Way To Do It, and the library can be focused on making that as nice as possible.
2. The generated classnames are much nicer to use with devtools (because they have the module name in them) than generated hashes
3. It's generally pretty tough to beat `.css` files when it comes to compiled asset size and performance, and especially when compared to the extra work of hashing at runtime
4. @mdgriffith recently ran some benchmarks and discovered that (at least in Chrome) animating based on the `style` attribute is actually like an order of magnitude _faster_ than animating based on keyframes, which surprised me - but animations are one of the areas where performance differences are most visible to the end user, so I think that deserves serious consideration.

We're basically moving to this at NRI anyway, but I'm curious to hear from folks who are currently doing something different.

@anagrius @sporto how would you feel about this?

**Comment by mdgriffith** [comment]
Small note on #4, I was looking specifically at color.

So, a css keyframe animation using just translate was super performant.  A css keyframe animation doing translate and modifying background color tanked pretty hard in chrome, and in that case animating background color and translate via manually setting inline styles beat it out handily.

Also, in further digging this behavior didn't show up in safari.  CSS animations were generally performant there.

I can share the benchmark in a bit if people would like.

**Comment by anagrius** [comment]
I think that is the way to go. CSS files all the way, IMO. But it doesn't address the issue of folder structure - I guess. I have been thinking about this for a while, It is really the same thing as keeping tests in a different directory. I am just of the mind that: Thinks that fit together, go together.
I am a "Clicking through the File Tree"-kind of guy (to my own dismay). So not having to traverse a big folder structure is a big deal for my personal productivity.

I didn't really want to make this a discussion about folder structure (I think there has been enough of those in the elm community :) ). What I would like is that we have the option of doing it according to taste. I realized that is counter to "One Way of Doing It". You are winning me over with the simplicity and how easy it is to make tools for when you _know_ where stuff if, but I just can't help but feeling, that it is a step back but the bad old days where javascript was in the javascript folder, images was in `img/` etc.

**Comment by sporto** [comment]
I quite like Html.Styled. This is something we have been experimenting with (https://github.com/xarvh/elm-styled-html) for while but never got to a mature point. This makes it very easy to get started.

On the other hand having only one way of doing things seems great as all the effort can be put in doing that way really nice. 

The classnames using the modules path is great, as it helps to find the corresponding Elm modules when inspecting the DOM.

**Comment by sporto** [comment]
BTW, there was discussion about having `test-dependencies` in elm.json for 0.19. https://gist.github.com/evancz/ae8890eef7cbfab84361e17eec71f3bd#file-app-json

Maybe you can discuss with Evan about the possibility of having arbitrary groups like ruby bundler in a gemfile, where you can have `development`, `test`, `build` or what ever you want. Could something like that remove the need for a different folder?

**Comment by rtfeldman** [comment]
Closing in favor of #327
