### ISSUE TITLE
Revert commit with breaking change prior to releasing 11.0.0

### ISSUE THREAD

**Issue by bobwhitelock** [rtfeldman/elm-css#306]
Congrats on releasing 10.0.0 @rtfeldman! I noticed https://github.com/rtfeldman/elm-css/commit/ebd4ccdd6c75298b53ec10364fc1c1bb7670cce8 didn't get un-reverted prior to the release, so thought I'd open this to remind us to do so before the next major release. Hope this is helpful, and apologies if this was intentional :slightly_smiling_face:.

**Comment by rtfeldman** [comment]
Bah, totally forgot - sorry!

Reverted in d034390e1205c95ead5ddf3947575e4e43eb917f on `master`

**Comment by rtfeldman** [comment]
@bobwhitelock fixed in 11.0.0.
