### ISSUE TITLE
elm-interface-to-json can't handle repos with dots in them

### ISSUE THREAD

**Issue by ahstro** [rtfeldman/elm-css#318]
I think? I have not been able to figure out where it comes from, so can't check the source of it either.

**Comment by ahstro** [comment]
Actually, looks like it's not working at all. Getting this error:

`/home/ahstro/home/dev/ahstro.github.io/elm-stuff/generated-code/rtfeldman/elm-css/elm-stuff/build-artifacts/0.18.0/ahstro/ahstro/3.0.0: /home/ahstro/home/dev/ahstro.github.io/elm-stuff/generated-code/rtfeldman/elm-css/elm-stuff/build-artifacts/0.18.0/ahstro/ahstro/3.0.0: getSymbolicLinkStatus: does not exist (No such file or directory)`

**Comment by rtfeldman** [comment]
@ahstro Can you file this on https://github.com/stoeffel/elm-interface-to-json instead? This will affect other projects that use it!
