### ISSUE TITLE
Validity checks

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#32]
This is not MVP, but at some point I'd like to have `elm-css` do some additional checks for invalid values (perhaps once the Declarations have been assembled, or perhaps sooner...waiting for Declarations arguably allows extra context and thus nicer error messages, but requires more regexp work).

Some checks that sound good:
- [x] Run a regex (`regex "^([a-fA-F]{3}|[a-fA-F]{6})$"` for hex colors) to confirm they're valid color values.
- [ ] Warn if there are any selectors defined with no properties; they won't do anything and should be deleted.
- [ ] Warn if the same property is declared multiple times within the same selector. All but the last declaration should be deleted.
- [ ] Warn if the same selector is declared multiple times within the same stylesheet. There are theoretically reasons it might be reasonable to support this, but more likely than not, this will just be error-prone. The Anti Footgun League says: complain about it.
- [ ] Warn if any MultiSelectors include multiple [Type Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors); these will for sure emit busted CSS.
- [ ] Warn if any class, id, or animation names are not [valid CSS identifiers](http://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors) - possible if you use strings instead of union types.
- [ ] Verify that [text-align](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align) and [text-align-last](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last) disallow the appropriate properties that the other doesn't support. This can't be fixed with type checking because of `left`, `right`, `top`, and `bottom` being overloaded as both keys and values.

**Comment by rtfeldman** [comment]
Now that `~` just resolves mixins, I think the properties themselves can handle these - and with context. Just need to have `InvalidStyle` build up an error message context instead of being a no-op so often, and have stuff like `prop1` incorporate the notion of adding to the error context.

Then we can get fail fast, nice error messages, etc.

**Comment by tolgap** [comment]
@rtfeldman While working on #105 I noticed that `propN` methods are sometimes used with multiple `type aliases` that do not have a notion of `warnings` attached to them, like `textDecoration3`:

```{elm}
textDecoration3 : TextDecorationLine compatibleA -> TextDecorationStyle compatibleB -> ColorValue compatibleC -> Mixin
textDecoration3 =
  prop3 "text-decoration"
```

So I left them untouched for the time being. Once we are sure that these types have error handling as well, we could incorporate `propN` functions to pass through warnings as well and that would clean up the code again.

**Comment by rtfeldman** [comment]
Yep, makes sense to me!

**Comment by rtfeldman** [comment]
Closing in favor of #327
