### ISSUE TITLE
Conflicting namespaces, when importing multiple stylesheets in the same view.

### ISSUE THREAD

**Issue by feluxe** [rtfeldman/elm-css#332]
Hi there!

I started fiddling with *elm-css* and I think it's really cool! But now I'm scaling and I ran into an issue which I couldn't figure to solve nicely.

Let's say I have a structure like this:

```
src
├── FooView.elm              
├── BarView.elm 
├── ...
└── Style
    ├── Index.elm         # Entry for the elm-css compiler. 
    ├── FooCss.elm        # Contains CSS for FooView.elm.
    ├── Foo.elm           # Contains (ids, classes) that are used in FooCss.elm
    ├── BarCss.elm        # Contains CSS for BarView.elm.
    ├── Bar.elm           # Contains (ids, classes) that are used in BarCss.elm
    ├── MiscCss.elm       # Contains CSS that is used across multiple Views.
    ├── Misc.elm          # Contains (ids, classes) that are used in MiscCss.elm
    └── ...               # Scaling further, more stylesheets...
```

The files above are similar to the ones in the example *(elm-css/examples/src/)*

* `Index.elm` is equivalent to `elm-css/examples/src/Stylesheets.elm`
* `FooCss.elm`, `BarCss.elm` and `MiscCss.elm` would be equivalent to `elm-css/examples/src/HomepageCss.elm`
* `Style.Foo.elm`, `Style.Bar.elm`, `Style.Misc.elm` would be equivalent to `elm-css/examples/src/SharedStyles.elm`

I run into an issue if I want to import multiple styles into one view.

E.g. if I put this in `src/FooView.elm`:

```
import Style.Foo
import Style.Misc

{ id, class, classList } =
    Style.Foo.fooStyleNamespace
```
Now  `id`, `class`, `classList` are bound to `Style.Foo` and blocked to be used with `Style.Misc`.

Is there a nice way to solve this with *elm-css*? If yes, I apologize for bothering you. If not I leave this here for discussion. :)

**Comment by rtfeldman** [comment]
Closing since namespace has been deprecated!
