### ISSUE TITLE
Cannot use elm-css with elm-mdl

### ISSUE THREAD

**Issue by grkuntzmd** [rtfeldman/elm-css#336]
`elm-mdl` requires that css be provided using the function

    Material.Options.css : String -> String -> Material.Options.Property c m

but there does not seems to be any way to convert elm-css `Html.Styled.Attributes.Attribute msg` to `(String, String)`.

**Comment by rtfeldman** [comment]
It's not possible to do that conversion; there is more information there than just `( String, String )` key-value pairs! For example, you can get these things in the mix:

* media queries
* pseudo-selectors
* global selectors from `Css.Foreign`

None of these are representable as key-value pairs, so unfortunately this conversion is not even theoretically possible. 😅 

Sorry!
