### ISSUE TITLE
Svg.Styled

### ISSUE THREAD

**Issue by edkv** [rtfeldman/elm-css#339]
`Html.Styled` is awesome, but are there any plans for adding `Svg.Styled`? I tried to implement it on top of `Html.Styled`, but this leads to runtime errors since `elm-css` adds classes using the [`className` property](https://github.com/rtfeldman/elm-css/blob/master/src/Html/Styled/Internal.elm#L315) and for Svg [the `class` attribute should be used instead](https://github.com/elm-lang/svg/blob/2.0.0/src/Svg/Attributes.elm#L228).

**Comment by rtfeldman** [comment]
Ah, good point! You can I'm totally open to adding `Svg.Styled` modules.

Want to take a crack at a PR?

**Comment by edkv** [comment]
@rtfeldman I'm implementing `Svg.Styled` and I've noticed that the `styled` function is defined in the `Html.Styled.Attributes` module. Is this really intended? It seems to me that `Html.Styled` is a better place for it since it works with nodes and not with attributes. Maybe we should move it?

**Comment by rtfeldman** [comment]
👍 I agree! Go ahead and move it.

The fix for https://github.com/rtfeldman/elm-css/issues/337 (namely making it so that if you provide multiple `css` attributes to the same element, only one has any effect) should be a breaking release anyway.

**Comment by rtfeldman** [comment]
Fixed by #342
