### ISSUE TITLE
Svg.Styled is needed or Html.Styled.Attributes.toUnstyled is needed

### ISSUE THREAD

**Issue by Stijnkool** [rtfeldman/elm-css#347]
Like `Html.Styled`, `Svg.Styled` is required:
- to use `Svg` elements inside `Html.Styled` elements.
- to be able to add styles to `Svg` elements

Is there a way to use `Svg` elements inside `Html.Styled` in the meantime?
I tried writing svg elements using the `node` and `attribute` functions from `Html.Styled`.
But `attribute` doesn't allow camelcase `viewBox`, and the related issue https://github.com/elm-lang/svg/issues/13 is closed.

**Comment by Stijnkool** [comment]
I am not sure if `Svg.Styled` is needed, `fromUnstyled` can be used to transform `Svg` into `Html.Styled`.
http://package.elm-lang.org/packages/rtfeldman/elm-css/12.0.0/Html-Styled#fromUnstyled

**Comment by edkv** [comment]
`Svg.Styled` is already implemented in the `html-styled` branch and will be available in the next release! 

Meanwhile, you can use `Css.asPairsDEPRECATED >> Html.Attributes.style` (note that I'm using the regular `Html` package here) to style your SVG with inline styles (or use `Css.Foreign`).

**Comment by rtfeldman** [comment]
Thanks! I agree, and this is already merged into `master` - will be available in the next release!
