### ISSUE TITLE
Move `Css.Colors` into separate package?

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#358]
Including `Css.Colors` as a convenience seemed like a good idea at the time, but now I'm thinking it's not worth cluttering up the `Css.` namespace with it.

Without `Css.Colors`, we'd have:

```
Css
Css.Media
Css.Foreign
```

I like that better. It makes sense to me that these would be separate modules, and that you'd start by learning `Css`, then `Css.Media`, then optionally `Css.Foreign`.

To access the nicer colors, I could publish something like `rtfeldman/nicer-css-colors` and link to it from the README.

Thoughts?

**Comment by mfeineis** [comment]
That's a good idea, convenient as they may be, the easy colors are not really necessary for the core package. I like how everybody who is doing Elm sponges up that `what-can-I-remove-to-make-it-better` attitude. I wish TC39 would take a hint from that - https://github.com/tc39/proposal-do-expressions, https://github.com/tc39/proposal-pipeline-operator, https://github.com/tc39/proposal-pattern-matching... why, just why? Why won't they find a way to remove features or just use Elm for that matter. Sorry this got out of hand :-)

**Comment by edkv** [comment]
I'm against this :) Named colors are the part of CSS so I would expect this package (or any similar) to provide them. I use at least `black` and `white` quite often. But why do we even need a separate module? Maybe move these functions directly to `Css`?

**Comment by rtfeldman** [comment]
> Maybe move these functions directly to `Css`?

That's interesting...yeah, we could group them all together under a docs heading. 🤔

**Comment by mfeineis** [comment]
Still not a fan, what's the problem with `hex "000000"` and `hex "ffffff"`?

**Comment by edkv** [comment]
@mfeineis No problems:) I just don't really see harm in including these functions.

**Comment by sporto** [comment]
I'm favour of moving this to another package. We have never used `Css.Colors` so at least for us it seems like unnecessary kilobytes. Besides it doesn't implement the level 2 colors so is not that useful.
