### ISSUE TITLE
Styling on body or html tag

### ISSUE THREAD

**Issue by hendriklammers** [rtfeldman/elm-css#359]
Is it possible to put styling on the body or html tag with this library? I couldn't find anything about it in the documentation.
For example: I would like to remove the default margin from the body.

**Comment by rtfeldman** [comment]
Yep! Check out http://package.elm-lang.org/packages/rtfeldman/elm-css/13.0.1/Css-Foreign#global 😄

**Comment by hendriklammers** [comment]
Ah great. Thnx!
