### ISSUE TITLE
Documentation needed for Css.Transitions

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#362]
https://github.com/rtfeldman/elm-css/pull/324 implemented CSS transitions. Great start!

However, we need lots of documentation before these can be released. 😄 

Anyone interested in contributing some?

**Comment by robertbasden** [comment]
Hi there! I would be interested in taking on this issue, any particular guidelines you would like followed? I will try and match comment style with the other documentation as much as possible.

**Comment by rtfeldman** [comment]
That would be fantastic! ❤️ 

Following the current style sounds like a good start; I'd be happy to give inline feedback on a PR!

**Comment by robertbasden** [comment]
Sweet! I will take a look and submit PR once I think its good for review.

**Comment by robertbasden** [comment]
PR is in - let me know your thoughts and ill amend as required!
