### ISSUE TITLE
Tests needed for Css.Transitions

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#363]
#324 implemented CSS transitions. Great start!

However, we need lots of tests before these can be released with any confidence. 😄

Anyone interested in contributing some?

**Comment by tsawan** [comment]
Hi there! I would like to contribute here. Let me know how best to start on this?

**Comment by tsawan** [comment]
I've started going through transitions source and tests for other modules.

**Comment by rtfeldman** [comment]
Awesome, thanks @tsawan!

The module just had documentation merged in https://github.com/rtfeldman/elm-css/pull/382 in case those are helpful!

**Comment by tsawan** [comment]
@rtfeldman please have a look at this gist and let me know if I am on the right track.
https://gist.github.com/tsawan/059301b64d5220fdecc26cd35a822d66

**Comment by tsawan** [comment]
@rtfeldman I guess exposing durationTransition was a mistake since I should only be testing public API. Let me know if it's ok to export Animatable(..) and  propToString from the Transitions.elm so I can try to finish this off?

**Comment by rtfeldman** [comment]
@tsawan Thank you for this, and really sorry I took so long responding!

I would definitely not change the `exposing` of the module. What I'd do instead is to render a trivial `stylesheet` all the way to a `String` (e.g. `"p { background-color: blue; }`) and then test the compiled string.

Check out `expectPropertyWorks` in `tests/Properties.elm` - I'd start by copying that, and then modifying it for your purposes!

**Comment by tsawan** [comment]
@rtfeldman I am a bit stuck on tests for functions that take TimingFunction (e.g,. background3). Since Css.Transitions.TimingFunction is not exposed, I can't add type signatures.

**Comment by tsawan** [comment]
@rtfeldman PR submitted.
