### ISSUE TITLE
Idea about Lazy

### ISSUE THREAD

**Issue by edkv** [rtfeldman/elm-css#364]
I have an idea how to improve Lazy API and still avoid #348:

```elm
lazy : (a -> Html msg) -> a -> Html msg
lazy fn arg =
    VirtualDom.lazy2 lazyHelp fn arg
        |> Unstyled


lazyHelp : (a -> Html msg) -> a -> VirtualDom.Node msg
lazyHelp fn arg =
    fn arg
        |> toUnstyled
```

VirtualDom compares arguments by reference in JS so we can safely pass `fn` to it. The problem is that `lazy` is implemented with the usage of `VirtualDom.lazy2` and `lazy2` will then use `VirtualDom.lazy3`... and it seems that there is no way to implement `lazy3` in which case it must use a different API. I don't know if it's worth it (or maybe there is a solution for `lazy3`?), just wanted to share this.

And here is the proof that it actually works https://ellie-app.com/kxHM94kNHa1/2. You should see a delay when you press the button, which is caused by an expensive computation in the view, after removing `lazy` on line 30.

**Comment by rtfeldman** [comment]
Yep, @mdgriffith introduced me to this technique - he's using it in `style-elements`.

I like the idea, and I think we should switch to it post-0.19 when `lazy` is going to go up to something like `lazy8`.

**Comment by edkv** [comment]
>I like the idea, and I think we should switch to it post-0.19 when lazy is going to go up to something like lazy8.

Ok, cool!
