### ISSUE TITLE
Super-strange elm-css/Chrome bug of "media query" in combination with "CSS style change"

### ISSUE THREAD

**Issue by heracek** [rtfeldman/elm-css#378]
Hi, we've found a super-strange bug when running `elm-css@13.0.1` in **Chrome v63.0.3239.132**.
Same bug occured on **macOS Sierra 10.12.6** and on other machine with **Windows 10**.
Bug is also in **Chrome Canary v65.0.3317.0**.

We were not able to replicate this bug on in other browser.

This bug occures when combining **media query** and **views that change `css` based on `model`**.

## Bug Demonstration

I created [Ellie example](https://ellie-app.com/embed/gQBcw4jjqa1/10) that demonstrates this.

### Description Demonstration

- there are few **responsive views** that change based screen width (using `@media (min-width: 700px)`)
- there is a **toggle** button, that changes background color after click (using `elm-css`)

Expected behaviour is that the **responsive views** does not influence the **toggle** button and vice versa.

### The Problem

When you click the **toggle** button few times then in some cases CSS for desktop will apply on mobile (or mobile CSS will apply on desktop) in Chrome.

### Screencast Demonstration

![elm-css-safari-vs-chrome-bug](https://user-images.githubusercontent.com/7502/34824670-c10f46d4-f6cf-11e7-81c5-01d978ce0f31.gif)

Safari works as expected, Chrome displays wrong CSS after few steps and clicking on the **toggle**.

### Bug Replication Steps

1. Open [the demonstration](https://ellie-app.com/embed/gQBcw4jjqa1/10) in Chrome and swith to **Results** tab.
1. Shrink and widen the window few times so you observer both mobile and desktop versions (break point is at 700px width).
1. Widen window to desktop version.
1. Click the **toggle** button 3 times (it should stay green).
1. Shrink to mobile version.
1. Click the **toggle** button few times.

Now you should see desktop CSS applied to mobile screen width.

## Analysis

Generated CSS seems ok. Here is diff of generated CSS ofter clicking on the **Toggle**:

<img width="562" alt="css-diff" src="https://user-images.githubusercontent.com/7502/34824798-377c1608-f6d0-11e7-91b4-f37534a9239f.png">

App `<style>...</style>` tag is updated properly and it works in all other browsers.
So I think there is no problem in CSS.

## Hypothesis

My hypothesis is that Chrome has some CSS cache and it can't handle change of `<style>...</style>`.

So maybe there is some way how to tell Chrome that it should invalidate the cache.
Or maybe it's a bug in Chrome.

**Comment by rtfeldman** [comment]
Wow, that's...really bizarre! It definitely seems like a bug in the browser. I'm not sure what we could do to work around that.

If you have any ideas, I'm open to them!

**Comment by heracek** [comment]
I tried to hack `toUnstyled` to use `keyedNode` with key containing whole style to replace `<style>` element on CSS change. And it didn't help.

What helped is to notify Chrome using `insertRule`. It's an ugly hack, but adding this helped:
```js
document.body.addEventListener('click', () => document.styleSheets[1].insertRule("body {}"));
```
https://ellie-app.com/embed/gQBcw4jjqa1/11

**Comment by rtfeldman** [comment]
Long-term, I've talked with Evan about having us be able to use `insertRule` directly. I presume that would address this, although I don't think it'll happen soon.

**Comment by rtfeldman** [comment]
Closing in favor of meta-issue https://github.com/rtfeldman/elm-css/issues/378

Thanks for the detailed report and potential fix @heracek!
