### ISSUE TITLE
Expose program et al.

### ISSUE THREAD

**Issue by ahstro** [rtfeldman/elm-css#381]
>The `Html.Styled`-docs says that it's a "Drop-in replacement for the `Html` module from the `elm-lang/html` package.", but when I use `import Html.Styled as Html`, I'm getting an error saying `Html.program` does not exist. Why does `Html.Styled` not expose all the same things as `Html`? Maybe the "drop-in replacement"-line should be changed if this is by design?

https://elmlang.slack.com/archives/C0HJVT881/p1517080261000066

**Comment by rtfeldman** [comment]
Not by design, just an oversight...`program` equivalents seem worth adding!

**Comment by ahstro** [comment]
Closed in ff06ba9821b04f5ad126976e01dd7227fde6a70e
Thanks! 😄
