### ISSUE TITLE
Any working example of using Css.Foreign (and global)?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rtfeldman/elm-css#383]
Hello!

I lost the entire evening digging through examples.

I have this simple `Stylesheets.elm` file:

```elm
module Stylesheets exposing (..)

import Css exposing (..)

global
    [ class LoginFormButton
        [ fontWeight normal
        , color (rgb 128 64 32)
        ]
    ]
```

And I compile it with `elm-css ./src/Stylesheets.elm`. No matter what I do, I get:

```
-- SYNTAX PROBLEM ---------------------------------------- ./src/Stylesheets.elm

I ran into something unexpected when parsing your code!

6|     [ class LoginFormButton
               ^
I am looking for one of the following things:

    a closing brace ']'
    whitespace

Detected errors in 1 module.                                        
Error: Errored with exit code 1
```

I digged into a various projects using elm-css, but all of them use deprecated `Css.File`.
I need to create css classes for an existing application, so clearly I need to expose some global classes, but so far I'm failing hard.

Is there anything I'm missing?

**Comment by midorikocak** [comment]
Following this.

**Comment by rlefevre** [comment]
Here is how I use them if this can be helpful: https://ellie-app.com/npLtqk4KZa1/1

```elm
module Main exposing (main)

import Css exposing (backgroundColor, hsl, padding, pct)
import Css.Foreign
import Css.Helpers exposing (toCssIdentifier)
import Html as Html
import Html.Styled exposing (Attribute, Html, div, styled, text, toUnstyled)
import Html.Styled.Attributes exposing (class, css)

type GlobalClass
    = Info
    | Error


globalStyleNode : Html msg
globalStyleNode =
    Css.Foreign.global
        [ Css.Foreign.html
            [ backgroundColor (hsl 0 0 0.94) ]
        , Css.Foreign.class Info
            [ Css.color (Css.hex "0000ff") ]
        , Css.Foreign.class Error
            [ Css.color (Css.hex "ff0000") ]
        ]


page : List (Attribute msg) -> List (Html msg) -> Html msg
page attributes children =
    styled div
        [ padding (pct 2) ]
        attributes
        (globalStyleNode :: children)


main : Html.Html msg
main =
    page []
        [ div [ class (toCssIdentifier Info) ]
            [ text "Some info." ]
        , div [ class (toCssIdentifier Error) ]
            [ text "Some error." ]
        ]
        |> toUnstyled
```

# Notes
- In real life, I would not use global classes to style some text like in this example. I would use them only for `html`, `body` or some web components that I cannot style with `Html.Styled.styled` (or for some rare performance issues).
- In Elm 0.19, `toString` will most likely be available only in debug mode as `Debug.toString`, so another method will have to be found for `toCssIdentifier` 
- You don't need to import `Html` and use `Html.Html` and `Html.Styled.toUnstyled` like in the `main` function of this example if you use `Html.Styled.program` or `Html.Styled.beginnerProgram`. I used it there to keep the example as short as possible.

**Comment by rtfeldman** [comment]
Thanks @rlefevre! It seems like your post answered the original question, so I'm gonna close this. 🙂
