### ISSUE TITLE
Chrome: subscription to Window.resizes interferes with media queries

### ISSUE THREAD

**Issue by fbedussi** [rtfeldman/elm-css#386]
# Scenario
Use Chrome browser.
There is a responsive app. 
Under the mobile breakpoint the main menu is a panel sliding in from the left. Above the breakpoint (desktop mode) the menu is a static sidebar. 
There is a subscription to `Window.resizes` to close the menu on window resize, in order to close the panel when crossing the breakpoint and switching from mobile to desktop mode:
```
Window.resizes (\{height, width} -> if model.menuOpen then CloseMenu else NoOp)
```
The app is visible here:
https://rss-reader-19af4.firebaseapp.com/
(login data: "test@test.com" with "password")

# Steps to reproduce
1- Start the app in desktop mode:
![desktopok](https://user-images.githubusercontent.com/9413715/37600803-a51e80a0-2b88-11e8-9a56-1123276d8fe8.jpg)
everything is fine, for example the hamburger icon has `display: none;` applied. 

2- Switch to mobile mode and open the menu:
![mobileok](https://user-images.githubusercontent.com/9413715/37600843-c3d6e92e-2b88-11e8-83b1-023b02ca42d7.jpg)
everything is fine, for example the hamburger icon has *not*  `display: none;` applied. 

3- Switch back to desktop mode:
![desktopbroken](https://user-images.githubusercontent.com/9413715/37600880-dcc444e0-2b88-11e8-82fb-33ef52ccbc53.jpg)
Now media queries are not applied correctly. Elements have the correct classes (the same as step 1), but media queries are not applied. 

The bug seems to affect Chrome only. 
Possibly related to
https://github.com/rtfeldman/elm-css/issues/378

**Comment by rtfeldman** [comment]
Yeah this also seems to be something we can't do much about, since we're generating the correct classes.

Hopefully switching to an `insertRule` implementation will address this. 🤞

**Comment by rtfeldman** [comment]
Closing in favor of meta-issue: https://github.com/rtfeldman/elm-css/issues/434
