### ISSUE TITLE
Split out Css.Elements

### ISSUE THREAD

**Issue by lukewestby** [rtfeldman/elm-css#40]
What do you think about separating keywords for selectors, properties, media queries, etc. into separate modules? I'm trying elm-css out on a personal project right now and I'd like to colocate each component's CSS with its view, but the html selector keywords clash with `elm-html`'s element functions. I'd love to be able to do:

```elm
import Html exposing (...)
import Css.Elements
import Css.Properties exposing (..)
import Css exposing (..)

-- ...

css =
  stylesheet { name = "example" }
    $ Css.Elements.body |$ Css.Elements.html
      ~ margin zero
    . Nav
      ~ padding (px 10)

-- ...
```

**Comment by rtfeldman** [comment]
Interesting...I'm definitely open to the idea!

I was hoping to avoid the "three imports to get anything done" situation that `Html` has (with `Html`, `Html.Attributes`, and `Html.Events`) but this is a compelling use case for `Css.Elements` in particular.

I'm okay with saying we should split out Elements, and then revisit other splits as specific use cases like this one arise.

**Comment by lukewestby** [comment]
Sounds great! Splitting out elements should definitely be sufficient, I hadn't thought about how more splitting might affect the docs and it's definitely good to avoid cluttering imports more than needed.

**Comment by rtfeldman** [comment]
Cool! I will take care of this.

**Comment by lukewestby** [comment]
Awesome, thanks for doing this!
