### ISSUE TITLE
Importing fonts from Google Fonts

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [rtfeldman/elm-css#446]
I could find no documentation of this, nor it's precense in any example, is this possible in elm-css? Or perhaps there's some obvious way to do it that I'm missing. 

I'm talking about an equivalent to 
`@import url('https://fonts.googleapis.com/css?family=Jura');`
or 
`<link href="https://fonts.googleapis.com/css?family=Jura" rel="stylesheet">`

**Comment by AlmightyFloppyFish** [comment]
Solved by using "node" in Html package 
`node "link" [ href "https://fonts.googleapis.com/css?family=Jura", rel "stylesheet" ] []`
and adding font normally using elm-css 

Sorry for bothering you with a question which turns out this package has nothing to do with

**Comment by Kurren123** [comment]
@AlmightyFloppyFish  thanks for reporting, I had the same question
