### ISSUE TITLE
(Suggestion) Make the `Styled.Html.styled` function lazy

### ISSUE THREAD

**Issue by Warry** [rtfeldman/elm-css#455]
Reading through the code, I was surprised that the `styled` function didn't seemed to be lazy at all. Hence the hash is calculated every time the function is called. 

current implementation:
https://github.com/rtfeldman/elm-css/blob/2064f1523be13f8647cbba954313b736e6f8d5c3/src/Html/Styled.elm#L301-L303

my suggestion:
```elm
styled fn styles =
    let
        styleAttribute =
            Internal.css styles
    in
        \attrs children ->
            fn (styleAttribute :: attrs) children
```

This would allow to cache the computation of the hash when declaring styled nodes at the top level, like:
```elm
myNode =
    Styled.Html.styled Styled.Html.div
        [ Css.displayFlex
        ]
```

It shouldn't radically change the performances, but it's free!

**Comment by rtfeldman** [comment]
Great idea @Warry!

I don't see any downsides...happy to accept a PR for this!

**Comment by Warry** [comment]
Sweet, happy to help :) The PR already exists at #456
