### ISSUE TITLE
Please upgrade to elm 0.19.0

### ISSUE THREAD

**Issue by adamgajzlerowicz** [rtfeldman/elm-css#464]
The following packages do not work with Elm 0.19.0 right now:

    rtfeldman/elm-css

I am just starting with elm and trying to get styles to work properly...
Thanks

**Comment by tolgap** [comment]
@adamgajzlerowicz its work in progress: https://github.com/rtfeldman/elm-css/pull/463

**Comment by adamgajzlerowicz** [comment]
Awesome - Thanks!
