### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by rokit** [rtfeldman/elm-css#501]
Examples aren't working.

Steps:
clone this repository
run `elm reactor`
navigate to `http://localhost:8000/examples/html-styled/Main.elm`

An error is shown:
```
-- UNKNOWN IMPORT -------------------------------- examples\html-styled\Main.elm

The Main module has a bad import: import Html Do you want the one from the elm/html package? If so, run this command to add that dependency to your elm.json file: elm install elm/html If you want a local file, make sure the `Html` module is in your src/ directory.
```
I tried clicking `index.html` instead but it was just blank.

**Comment by AleXoundOS** [comment]
You need to navigate to `examples/html-styled` first. Then run `elm reactor` from there. Then it works.

Notice different `elm.json` project configuration files in the root of the project and in `examples/html-styled`. The example does not compile with different package versions from the root project.

But I agree that there should be an instruction for running examples or a guide for elm-css in general.

**Comment by rokit** [comment]
Oh, I see. Thanks for clearing that up.
