### ISSUE TITLE
Migration tool: convert a CSS file to en elm-css file using PostCSS's css-to-AST

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#52]
This would be a great way to convert existing css files to elm-css files. Since [PostCSS](https://github.com/postcss/postcss) already has a JS tool for taking in a CSS file and turning it into an AST, this could presumably be accomplished by starting with that and then outputting an elm-css file from that AST.

**Comment by colinwahl** [comment]
Is this still something you would like done? I would give it a shot!

**Comment by rtfeldman** [comment]
Yes, that would be amazing!!!

**Comment by rtfeldman** [comment]
Relevant similar project: https://github.com/eeue56/sass-to-elm

**Comment by colinwahl** [comment]
After doing some research this weekend, I think that the best approach would be to write a custom PostCSS stringifier to generate elm-css from the AST. I'll try to take a stab at it tonight

**Comment by attekei** [comment]
Any progress on this @colinwahl?

I'd like to see something like [HTML to Elm](http://mbylstra.github.io/html-to-elm/), because I feel sometimes that I'm wasting too much time converting existing CSS snippets to Elm code 🙂 

If you don't have time, I also could try it, because I'm interested in getting some experience of working with ASTs. The biggest concern is that every single time there is new functionality / breaking changes in elm-css, the converter would be out of date. Do you have any ideas how to tackle that problem?

**Comment by eeue56** [comment]
I have sass-to-elm here -> https://github.com/eeue56/sass-to-elm

but I haven't touched it in a while

**Comment by attekei** [comment]
@eeue56 Cool! I looked at the PostCSS stringifiers, but seems that PostCSS AST is not abstract enough for making conversion to Elm easy... so maybe I simply create a frontend for sass-to-elm and maybe create some PRs to sass-to-elm if and when I find out-of-date stuff.

**Comment by eeue56** [comment]
Sass-to-elm has a webfrontend :)

**Comment by MarkNijhof** [comment]
Does something like this exist for SCSS to Elm-CSS? Or plain CSS to Elm-CSS has that been created?

**Comment by MarkNijhof** [comment]
Ah SASS will compile SCSS it seems

**Comment by midorikocak** [comment]
following

**Comment by rtfeldman** [comment]
I'm gonna close this for now. If anyone wants to start work on a project like this, please open a new issue!

**Comment by michaeljones** [comment]
Just to note, I did some work on a tool for this a while back though it is unpolished and we haven't used it much ourselves: https://github.com/Zaptic/css-to-elm-css

I might be doing so soon though.
