### ISSUE TITLE
Dependency (Skinney/murmur3 2.0.8) package corrupted

### ISSUE THREAD

**Issue by lok0613** [rtfeldman/elm-css#527]
I was trying recently with my `elm v0.19.1` : `~$ elm install rtfeldman/elm-css`
And I got these lines shown to my terminal:

```bash
Here is my plan:

  Add:
    Skinney/murmur3       2.0.8
    rtfeldman/elm-css    16.0.2
    rtfeldman/elm-hex     1.0.0

Would you like me to update your elm.json accordingly? [Y/n]: y
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for Skinney/murmur3 2.0.8 from:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it looks like the hash of the archive has changed since publication:

  Expected: 81a0bada79740ae806df04b1bb14a7d64f763ac5
    Actual: 931398ec656078e26b2e29520cd283ffe6e8e441

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
```

So let's check out what happened with the dependency, goto https://github.com/robinheghan/murmur3/tags
As we can see 2.0.8 was tagged on 19 Sep 2018, just wondering what could be the reason the hash just suddenly changed (if I get the meaning from my terminal)?

**Comment by roryc89** [comment]
I believe this is due to repo ownership transfer: https://github.com/robinheghan/murmur3/issues/5

**Comment by lok0613** [comment]
thanks, @roryc89 , I will just close this issue for avoiding duplication.

**Comment by rtfeldman** [comment]
If you update to `elm-css` 16.1.0, this issue should be gone!

**Comment by maxfarseer** [comment]
Hello @rtfeldman , what can we do, if we can't update elm-css to last one? (we have elm 0.18 project)

**Comment by rtfeldman** [comment]
@maxfarseer I don't plan to back-update older versions, but Robin has published https://package.elm-lang.org/packages/robinheghan/murmur3/latest/ now, so you can always fork an 0.18 release of `elm-css` and change the murmur3 dependency to that!
