### ISSUE TITLE
CSP nonce support (to be able to protect against XSS attacks)

### ISSUE THREAD

**Issue by jonathanmoregard** [rtfeldman/elm-css#569]
My company uses elm-css extensively. We need to be able to support CSP without unsafe-inline, in order to be security compliant. Elm-css generates inlined css-styles, which are blocked by the CSP-policy we need to implement.

There is a way to get around this, using [nonces](https://content-security-policy.com/nonce/). A nonce is a per-request cryptographically secure random value that is set as an attribute in the <style> tag. 

One way to go about this would be to add a function similar to [toUnstyled](https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/Html-Styled#toUnstyled) which also accepts a nonce. It's unclear to me what the best way to pass the nonce would be. This would turn the autogenerated elm-css style tag from <style> {elm-css-stuff} </style>, to <style nonce={passed nonce}>{elm-css-stuff}</style>.

**Comment by rtfeldman** [comment]
Cool, makes sense! 👍 

I'd be happy to accept a PR for this. I think calling the function `toNonceUnstyled` would make sense.

**Comment by rtfeldman** [comment]
Published as 17.1.0

**Comment by pawelpacana** [comment]
@jonathanmoregard Have you perhaps figured out how to best pass a nonce? 

Any attempt to pass server-generated nonce seem futile to me when the style tag is not rendered on server too. The reason for that is nonce should be hidden and browser does a lot to not reveal it: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding

With a nonce passed from server to Elm app via flags, we'd make it visible to the attacker. And thus defeat the purpose of CSP with nonce in first place: https://content-security-policy.com/nonce/. Is there any other option? Am I'm missing something obvious here?

**Comment by pawelpacana** [comment]
> I'm thinking, start the Elm app inside of an anonymous function and let the server write the nonce directly into the flags argument. Would this hide the nonce? Perhaps I'm also missing something

My bad. I've conflated _passing nonce via flags_ with _passing nonce via element attributes so that flags could read it_.

**Comment by pete-murphy** [comment]
We're trying to add nonces to `elm-css`-generated `<style>` tags, and are running into an issue that is not resolved by #570.

We're using [`elm-form`](https://github.com/dillonkearns/elm-form/blob/982706503bbd24ee2768e1815f62a783eac2ed06/src/Form.elm#L1085)'s `Form.renderStyledHtml`, which calls `Html.Styled.Lazy.lazy4`, which calls `VirtualDom.Styled.lazy4`, which calls `VirtualDom.Styled.toUnstyled`.

We need to use `toNonceUnstyled` to pass the nonce of course, but there's no way to do this currently even if `Form.renderStyledHtml` took an optional `nonce`: it uses `Html.Styled.Lazy` which does not expose any way of passing the nonce through to the `VirtualDom.Styled` internals.

Unless I'm missing something, I think for CSP nonce support we would need to add `Html.Styled.lazy*` and `VirtualDom.Styled.lazy*` variants that take a nonce as argument (and call `toNonceUnstyled` internally).
