### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by sagarbehere** [rtfeldman/elm-css#575]
[newbie here]

On the [Html.styled](https://package.elm-lang.org/packages/rtfeldman/elm-css/17.0.5/Html-Styled) page, in the documentation for the `styled` function, is the code snippet
```
view model =
    [ text "These two buttons are identical:"
    , bigButton [] [ text "Hi!" ]
    , button [ css [ padding (px 30), fontWeight bold ] ] [] [ text "Hi!" ]
    ]
```
It seems like the `button` function here is taking 3 lists as arguments, however the [button documentation](https://package.elm-lang.org/packages/elm/html/latest/Html#button) says that the `button` function takes 2 lists as arguments. So there seems to be an extra `[]` argument in that documentation snippet, which could be removed.

**Comment by rtfeldman** [comment]
Fixed, thanks @sagarbehere!
