### ISSUE TITLE
hsl and hsla functions

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#65]
We should have `hsl` and `hsla` functions that:

* Compile to `hsl()` and `hsla()` in CSS, respesctively. These are supported in [IE9+](http://caniuse.com/#feat=css3-colors), which makes them reasonable to include as a passthrough compile without (for example) converting to `rgb` behind the scenes.
* Records warnings if you pass numbers outside the acceptable range for these values (see how `rgb` and `rgba` do this for examples)
* Have elm-test tests in `test/Properties.elm` to verify that they can be used as intended.
* Have elm-check tests like what `rgb` and `rgba` have to verify that the warnings work.

**Comment by lukewestby** [comment]
I can do this one later tonight or tomorrow. Haven't written any Elm yet this week and it's making me grumpy :smile:

**Comment by rtfeldman** [comment]
These exist now. Thanks @lukewestby! :smiley_cat:
