### ISSUE TITLE
rgbaFromHex

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#68]
This needs to be implemented: https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L635-L643

Semantics:
* Should work with hexadecimal strings of length 3, 4, 6, or 8 (the 4 and 8 would include alpha, just like in CSS)
* If you give it a crazy value, like you use non-hexadecimal chars or a crazy length, it should return appropriate warning messages

Relatedly, there should probably also be a `rgbaFromHsla` that works similarly except for HSLA colors.

**Comment by lukewestby** [comment]
These functions should return a `Color` property with an `rgba(r,g,b,a)` value?

**Comment by rtfeldman** [comment]
It's actually that I changed `Color` to include `red`, `green`, and `blue` values, so you can now go `(rgb 22, 23,224).red` and get back `22`. This lets people do color mixing and such.

This is where the function lives now: https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L844-L854

Incidentally, here's the equivalent for `hsl` and `hsla`: https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L860-L867

**Comment by lukewestby** [comment]
got it! i can do this one tonight or tomorrow.

**Comment by rtfeldman** [comment]
Awesome! :smile_cat:

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/rtfeldman/elm-css/issues/76 cc @lukewestby - turns out having the records have a `color : Color` field (as in `Color` from core) will be more beneficial to people writing generic color mixing libraries, and I think it makes more sense to optimize for that use case than for the "pulling out `red`, `green`, or `blue` on an individual basis" use case.

**Comment by lukewestby** [comment]
sweet! that's awesome :metal:
