### ISSUE TITLE
It should be possible to somehow do maths with Units

### ISSUE THREAD

**Issue by eeue56** [rtfeldman/elm-css#72]
e.g

```elm
swimlaneWidth = px 150
pos1 = swimlaneWidth + (px 50)
pos2 = swimlaneWidth * 2
```

Obviously can't use `+`, but some other operator

**Comment by rtfeldman** [comment]
Hm...suppose the operator is `|+|` (let's say) - what happens if you do this? `(em 5) |+| (px 10)`?

**Comment by rtfeldman** [comment]
Oh, actually I might be able to make that a type error. I'll give it a shot.

**Comment by rtfeldman** [comment]
Totally works! 62e865704cbda6d702dfb7a21cc59c93f8523cb7

And the type errors are helpful too!

<img width="1020" alt="screen shot 2016-01-25 at 1 22 53 am" src="https://cloud.githubusercontent.com/assets/1094080/12544075/4acc173c-c304-11e5-972f-3f1d089e727b.png">

**Comment by rtfeldman** [comment]
So this NRI Sass code (with class names changed)...

```sass
.foo
  margin-right: 10px
  padding-top: (42px - 14px)/2 // Container height minus font height over 2

.bar
  right: -(140px + 17px) // element width + desired margin
  top: 8px
```

...can now be done in elm-css as of https://github.com/rtfeldman/elm-css/commit/62e865704cbda6d702dfb7a21cc59c93f8523cb7

```elm
(.) Foo
    [ marginRight (px 10)
    , paddingTop: ((px 42) |-| (px 14)) |/| (px 2) -- Container height minus font height over 2

(.) Bar
    [ right ((px 140) |+| (px 17)) |*| (px -1) -- element width + desired margin
    , top (px 8)
    ]
```

Only two differences are:

* You have to divide by `2px` instead of `2`. That's a bit strange but unavoidable.
* There's no `negate` equivalent. I think that's fine for now.

**Comment by eeue56** [comment]
Seems good to me. It's also worth noting that `em` can be turned into `px` based off [this table](http://v1.jontangerine.com/silo/css/pixels-to-ems/) but I wouldn't worry about it too much.
