### ISSUE TITLE
`class` from helpers should take a list

### ISSUE THREAD

**Issue by eeue56** [rtfeldman/elm-css#73]
e.g

```elm
div 
  [ class [ Swimlane, swimlaneType ] ]
  ]
```
where `swimlaneType : CssClasses`

right now I have to do

```elm

div
        [ classList
            [ (classType, True)
            , (Swimlane, True)
            ]
        ]
```

**Comment by rtfeldman** [comment]
Ah, I see - the difference is that in elm-html's version of things, you can do this trivially because it takes a `String`. I'm on board; will change in the next release. :+1:
