### ISSUE TITLE
elm-css-webpack-loader

### ISSUE THREAD

**Issue by tcoopman** [rtfeldman/elm-css#74]
First of all, very nice project!
I'm just trying it out for the first time and I got it working smoothly. 

But now I was thinking that it would be nice to have a webpack loader (or even integrate this with the elm-webpack-loader).
I know that this package is not ready yet, so this kind of idea is probably not yet on the roadmap, but it might be nice to already have a discussion about it.

For me the nicest thing would be that the loader would recompile the css file on changes and that it is able to pipe into the file-loader, so you can get hashed file names.

**Comment by rtfeldman** [comment]
:+1: Makes sense to me!

There's already an index.js which exposes the necessary hooks to create a Webpack loader; if someone wants to take a stab at it, please comment here to avoid duplicated effort. :smile_cat:

**Comment by ulrikaugustsson** [comment]
I created this gist: https://gist.github.com/ulrikaugustsson/684dfaa7b83147c8035f am I starting to get close or is this really far off from what would be required for a loader?

I stole most of the code from elm-webpack-loader

**Comment by rtfeldman** [comment]
@ulrikaugustsson looks like a good start! I wouldn't hardcode `src/` though. :wink:

**Comment by tcoopman** [comment]
@ulrikaugustsson any progress on this? If not, I'd like to take a look at it.

**Comment by ulrikaugustsson** [comment]
@tcoopman You can take it over, I don't know enough about webpack loaders to do this in a good way and I don't have the time either.

**Comment by tcoopman** [comment]
Ok, I already have a local version working, I'll try to push it this week to github so that we can make something out of it.

**Comment by ulrikaugustsson** [comment]
@tcoopman Did you get this working?

**Comment by tcoopman** [comment]
I've got something basic working yes.
I'll try to publish it on github this weekend

**Comment by rtfeldman** [comment]
@tcoopman any update on this?

**Comment by tcoopman** [comment]
I have a draft version working
https://github.com/tcoopman/elm-css-webpack-loader/blob/master/README.md
I didn't have time last week to further look into it. I'll try today or
tomorrow to have a working version ready for npm

**Comment by rtfeldman** [comment]
Awesome! :smiley_cat:

**Comment by tcoopman** [comment]
Didn't find time this weekend, going to do my best this week...

**Comment by tcoopman** [comment]
@rtfeldman is it possible to to build the css without writing it to a file, but just get the css output back? This is going to be cleaner for webpack, to pass it to an other loader (css-loader for example)

**Comment by eeue56** [comment]
@tcoopman have a look at how I implemented compileToString for node-elm-compiler

**Comment by tcoopman** [comment]
@eeue56 Thanks!

I've pushed a basic working version.
I haven't released it as a npm package yet, I'm waiting for the #87 to be fixed so that the examples work out of the box.

**Comment by tcoopman** [comment]
I've just published version 1 of the elm-css-webpack-loader: https://www.npmjs.com/package/elm-css-webpack-loader with lots of thanks to @roman!
