### ISSUE TITLE
Can elm-css be used in Elm files?

### ISSUE THREAD

**Issue by kittykatattack** [rtfeldman/elm-css#83]
Hello!

Just a quick question: is `elm-css` intended to be a stand-alone, or can it be used in Elm files as a substitute for `Html.Attributes`?

**Comment by igrep** [comment]
I'm not sure this is officially supported, but https://github.com/rtfeldman/elm-css/blob/master/src/Html/CssHelpers.elm seems to help you.
I learned by searching this repository with "Attribute".

**Comment by rtfeldman** [comment]
Not for all attributes, but yeah, that's the idea - you import the helpers and then they shadow `id`, `class`, and `classList` with drop-in replacements that work with your union types and/or namespaces.

**Comment by kittykatattack** [comment]
Thanks, I will try that!
I'm doing my first big production Elm app, and the only headache has been the silent failure of CSS code.
This library will really help :)

**Comment by rtfeldman** [comment]
Since this has been answered, I'm gonna close it!
