### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by lukewestby** [rtfeldman/elm-css#86]
Should the command line tool be supported for node < v4? The current implementation uses template strings which aren't implemented in < v4 so CI is failing for those runtimes.

**Comment by eeue56** [comment]
I'm torn. Happy to remove template strings if we want to support old node, but I really think that supporting 4+ is fine. There's a few posts talking about how 0.12 still has wide usage, but I don't think those companies are the ones using Elm or interested in using elm-css.

**Comment by lukewestby** [comment]
I agree. I think 0.12 having wide usage is more a concern for server-oriented modules than it is for tooling-oriented ones.

**Comment by eeue56** [comment]
What do you think @rtfeldman ?

**Comment by rtfeldman** [comment]
Yeah, I think 4+ is fine. :smile:
