### ISSUE TITLE
Can't import Html.CssHelpers

### ISSUE THREAD

**Issue by SerialVelocity** [rtfeldman/elm-css#87]
Hey,

I'm having trouble with your 1.0.0. I need to manually modify your elm-package.json to have more exposed modules. Specifically ```Html.CssHelpers```, and ```Css.Namespace```. There's probably a tonne but I've only just started looking at the library :)

Am I using the library incorrectly or is the elm-package.json out of date?

Cheers,
SerialVelocity

**Comment by eeue56** [comment]
You're not wrong. There used to be a css-helpers package, but I'm not sure of @rtfeldman's long term plan. Maybe worth opening a PR for it?

**Comment by eeue56** [comment]
cc @rtfeldman this is a slight blocker :dart:

**Comment by jgillich** [comment]
This is fixed and can be closed, right?

**Comment by SerialVelocity** [comment]
Possibly. I saw ```Css.Namespace``` was removed again. What has it been replaced by?

**Comment by jgillich** [comment]
Nevermind, `Css.Namespace` still appears to be missing..

**Comment by SerialVelocity** [comment]
It was added by e825047f but removed again by ec9661d5

**Comment by eeue56** [comment]
`Css.Helpers.namspace` now has `.rules`, which is the scoped version of the old Css.Namespace.namespace

**Comment by jgillich** [comment]
Is the example in the README supposed to work?
```
Detected errors in 1 module.
-- TYPE MISMATCH ------------------------------------------ ./src/Stylesheet.elm

`namespacer` is being used in an unexpected way.

42│   (stylesheet << namespacer.rules)
                     ^^^^^^^^^^
Based on its definition, `namespacer` has this type:

    { class : ..., classList : ..., id : ..., name : ... }

But you are trying to use it as:

    { b | rules : ... }

```

**Comment by eeue56** [comment]
Not with 1.0.0 - I haven't pushed it yet since I'm trying to make sure that the next release will work for sure :)

**Comment by jgillich** [comment]
Ah I see, thanks!

**Comment by jessitron** [comment]
In 2.0.0, the solution is:

`elm package install rtfeldman/elm-css-helpers`

This contains Html.CssHelpers

and then the function of relevance is withNamespace:

`(id, class, classList) = Html.CssHelpers.withNamespace "mynamespace"`

This is necessary to use the CSS classes in a typesafe way.
Which is totally not obvious and can we please add this to the README?

**Comment by eeue56** [comment]
Yup! can you please make a PR for this?

**Comment by jessitron** [comment]
done: https://github.com/rtfeldman/elm-css/pull/110

**Comment by rtfeldman** [comment]
Thanks @jessitron! 🎉
