### ISSUE TITLE
margin: auto

### ISSUE THREAD

**Issue by chrisbuttery** [rtfeldman/elm-css#9]
It would be great if the various margin declarations accepted `auto` as a value as well as `number`.
I'd be keen to see how you could solve this (with Elm), so I could potentially help with other properties.

**Comment by rtfeldman** [comment]
Unfortunately, unlike something like `display auto` and `display inline`, there's no way to make both `marginLeft 5 px` and `marginLeft auto` compile; either `marginLeft` takes one argument or it takes two.

Thus far `margin` is the only property in the CSS spec I've encountered that accepts either `auto` or a length value, so I'm leaning towards special-casing the `auto` case with something like `~ marginLeftAuto` etc.

Another way to go would involve making units into functions, so you'd have stuff like `marginLeft (px 5)` instead of `marginLeft 5 px` but then the DSL gets less nice for every other case just to make `margin` with `auto` nicer, which doesn't seem worth it.

**Comment by chrisbuttery** [comment]
Yeah after noodling about I realised the same thing. Perhaps we do roll with something like `marginXAuto` ( `x` being `Top`, `Right`, `Bottom` and `Left` ). I'll try and look at that in a few days (on a train ride to Seattle) and make a PR if you like ?

**Comment by rtfeldman** [comment]
:+1: Sounds awesome!

**Comment by rtfeldman** [comment]
Found another case: [border widths](https://developer.mozilla.org/en-US/docs/Web/CSS/border-width)

I'm not thrilled with it, but maybe `marginLeft (px 5)` is as good as it gets here.

**Comment by rtfeldman** [comment]
To elaborate, in the border case the `marginLeftAuto` thing doesn't really scale.

You have things like:

```elm
border thick solid (hex "CCFFFF")
borderLeft (px 5) solid (rgb 200 100 0)
```

Supporting all the different combinations of `border` as well as `margin` as well as `outline`, plus `height` and `width`, sounds unwieldy.

**Comment by rtfeldman** [comment]
Upon further consideration, I actually like the idea of aliasing `xx = 0` and then doing by convention:

```elm
marginLeft 5 px
marginLeft xx auto
borderLeft 5 px solid (rgb 200 100 0)
borderLeft xx thick solid (rgb 200 100 0)
```

So `xx` would be shorthand for "there's no relevant number here," and it would get ignored in the output.

**Comment by rtfeldman** [comment]
Hrm, that creates other problems though. For example, I like the idea of having different functions that correspond to the different arities that CSS offers:

```elm
-- margin (px 4)
-- compiles to
-- margin: 4px;
margin : Length -> Value

-- margin2 (px 4) auto
-- compiles to
-- margin: 4px auto;
margin2 : Length -> Length -> Value

-- margin4 (px 4) (px 8) (px 4) (px 12)
-- compiles to
-- margin: 4px 8px 4px 12px;
margin4 : Length -> Length -> Length -> Length -> Value
```

Those get pretty weird if you have to double the number of arguments. Which one is `margin4` at that point - the one that takes 4 arguments (`number -> Units -> number -> Units`) and compiles down to 2, or the one that takes eight arguments and compiles down to 4?

Seeing the `(px 5)` style in a bigger stylesheet, I feel like I could get used to it:

```elm
    stylesheet { name = "homepage" }
        $ header
            ~ backgroundColor (rgb 90 90 90)
            ~ boxSizing borderBox
            ~ padding (px -80)

        $ nav
            ~ display inlineBlock
            ~ paddingBottom (px 12)

        . NavLink
            ~ margin (px 12)
            ~ color (rgb 255 255 255)

        # ReactiveLogo
            ~ display inlineBlock
            ~ marginLeft (px 150)
            ~ marginRight (px 80)
            ~ verticalAlign middle

        # BuyTickets
            ~ padding (px 16)
            ~ paddingLeft (px 24)
            ~ paddingRight (px 24)
            ~ marginLeft (px 50)
            ~ color (rgb 255 255 255)
            ~ backgroundColor (rgb 27 217 130)
            ~ verticalAlign middle
```

**Comment by rtfeldman** [comment]
For completeness's sake, here are two other things I tried:

```elm
    stylesheet { name = "homepage" }
        $ header
            ~ backgroundColor (rgb 90 90 90)
            ~ boxSizing borderBox
            ~ padding (-80 $ px)

        $ nav
            ~ display inlineBlock
            ~ paddingBottom (12 $ px)

        . NavLink
            ~ margin (12 $ px)
            ~ color (rgb 255 255 255)

        # ReactiveLogo
            ~ display inlineBlock
            ~ marginLeft (150 $ px)
            ~ marginRight (80 $ px)
            ~ verticalAlign middle

        # BuyTickets
            ~ padding (16 $ px)
            ~ paddingLeft (24 $ px)
            ~ paddingRight (24 $ px)
            ~ marginLeft (50 $ px)
            ~ color (rgb 255 255 255)
            ~ backgroundColor (rgb 27 217 130)
            ~ verticalAlign middle
```

...and then the "abuse the parser" version of that:

```elm
    stylesheet { name = "homepage" }
        $ header
            ~ backgroundColor (rgb 90 90 90)
            ~ boxSizing borderBox
            ~ padding (-80$px)

        $ nav
            ~ display inlineBlock
            ~ paddingBottom (12$px)

        . NavLink
            ~ margin (12$px)
            ~ color (rgb 255 255 255)

        # ReactiveLogo
            ~ display inlineBlock
            ~ marginLeft (150$px)
            ~ marginRight (80$px)
            ~ verticalAlign middle

        # BuyTickets
            ~ padding (16$px)
            ~ paddingLeft (24$px)
            ~ paddingRight (24$px)
            ~ marginLeft (50$px)
            ~ color (rgb 255 255 255)
            ~ backgroundColor (rgb 27 217 130)
            ~ verticalAlign middle
```
These seemed like they'd take about as much getting used to as `(px 5)`, except they're more verbose.

**Comment by rtfeldman** [comment]
Okay, I went with the `(px 5)` approach - implemented in https://github.com/rtfeldman/elm-css/pull/33

It's a bit less aesthetically pleasing, but it's way simpler. Thanks for raising the issue @chrisbuttery!

**Comment by chrisbuttery** [comment]
Here's a little something from my sandbox.

I've created a `px` function to return a string. e.g. `"20px"`

```
px : number -> String
px num =
  (toString num) ++ "px"
```

I then changed the `width` and `margin` functions to accept a String, like so.

```
width : String -> Attribute
width =
  attr1 "width" (\str -> str)


margin : String -> Attribute
margin =
  attr1 "margin" (\str -> str)


marginTop : String -> Attribute
marginTop =
  attr1 "margin-top" (\str -> str)


marginRight : String -> Attribute
marginRight =
  attr1 "margin-right" (\str -> str)


marginBottom : String -> Attribute
marginBottom =
  attr1 "margin-bottom" (\str -> str)


marginLeft : String -> Attribute
marginLeft =
  attr1 "margin-left" (\str -> str)
```

As `attr1` expects a translation function, I'm just using `(\str -> str)` to return the param for now.

Now the syntax is very familiar.
If the value of String is incorrect `margin "foo"`, the browser will obviously render incorrect styles.

```
. FormFoo
  ~ marginLeft "auto"
  ~ marginRight (px 50)
  ~ marginTop "inherit"
  ~ marginBottom "5px"
  ~ width (px 400)

. FormBar
  ~ margin "auto"
  ~ margin "20px 20px 20px"
  ~ margin "1px 2px 3px 4px"
  ~ margin (px (50 * 2))
  ~ width "200px"
```

What are your thoughts on this ?

**Comment by chrisbuttery** [comment]
This was pretty much the desired effect I was after.

```
|.| FormSlim
  |-| margin "0 auto"
  |-| width (px 400)
```

![screen shot 2015-12-23 at 7 46 03 pm](https://cloud.githubusercontent.com/assets/121675/11989196/da8dd59c-a9ad-11e5-9065-50306deaa56c.png)

**Comment by chrisbuttery** [comment]
@rtfeldman This was pretty much the desired effect I was after.

```
|.| FormSlim
  |-| margin "0 auto"
  |-| width (px 400)
```

![screen shot 2015-12-23 at 7 46 03 pm](https://cloud.githubusercontent.com/assets/121675/11989196/da8dd59c-a9ad-11e5-9065-50306deaa56c.png)

**Comment by rtfeldman** [comment]
@chrisbuttery That's pretty much where I ended up (check out the current README for examples).

Here's how your sample would look once all the `margin` functions have been implemented:

```elm
. FormFoo
    ~ marginLeft auto
    ~ marginRight (px 50)
    ~ marginTop inherit
    ~ marginBottom (px 5)
    ~ width (px 400)

. FormBar
    ~ margin auto
    ~ margin4 (px 1) (px 2) (px 3) (px 4)
    ~ margin (px (50 * 2))
    ~ width (px 200)
```

Note that thanks to various union types, we already have stricter type-checking than Strings for these...on current `master` you can do `~ width auto` or `~ width inherit` or `~ width (px 5)` but if you try to do `~ width none` or `~ width "hamburger"` you'll get a type error. :smile_cat:

**Comment by rtfeldman** [comment]
I also added `zero` which compiles to a bare `0`, because that comes up a lot.

```elm
$ button
    ~ margin zero
```

...compiles to:

```css
button {
    margin: 0;
}
```

**Comment by chrisbuttery** [comment]
Oh nice! :+1: 

Dang, sorry I was late to the party, I only got time to look at this now.

**Comment by rtfeldman** [comment]
Thanks for surfacing it! I think we ended up with the right API taking all the design constraints into account.
