### ISSUE TITLE
How to use the elm-css tool when installing from elm packages?

### ISSUE THREAD

**Issue by nikgraf** [rtfeldman/elm-css#91]
The only way I got it working was doing something like this:

https://github.com/belle-ui/elm-belle/commit/e5c46ef847236ad9b8e5e86e5d016e35f0d38a33#diff-04c6e90faac2675aa89e2176d2eec7d8R28

This was hard to find out. Is there better way? If not I'm happy submit a PR to the readme …

**Comment by rtfeldman** [comment]
You can do `npm install -g elm-css` and then run `elm-css Stylesheets.elm` to compile the files.

Check out https://github.com/eeue56/json-to-elm/tree/master/elm for an example Stylesheets.elm file, or the [`examples`](https://github.com/rtfeldman/elm-css/tree/master/examples) folder in this repo!

**Comment by nikgraf** [comment]
Will do that, although it would be super cool to avoid npm at all when using Elm :smile:
