### ISSUE TITLE
No  `String -> MediaQuery` function for custom media queries

### ISSUE THREAD

**Issue by jbalboni** [rtfeldman/elm-css#92]
Hi,

I'm trying to use media queries like this:

```
@media (max-width: 768px) {
    ...
}
```

I'm new to Elm, so I could be missing it, but it looks like only queries like `@media "print"` are supported. Is that correct? Is there any way for me to use more generic functions to generate the right output?

Thanks!

**Comment by lukewestby** [comment]
Hey! You can use the `media` function to nest style blocks under a media rule https://github.com/rtfeldman/elm-css/blob/51813109f7ba3a2f239a011bbdcf6d4cb2b12d0e/src/Css.elm#L3525-L3534

**Comment by jbalboni** [comment]
@lukewestby This is what I see for that function in the 1.1.0 tag, which seems like it's only allowing you to pass `MediaQuery` values to the `media` function, and those values are only the different media types (print, screen, etc).

https://github.com/rtfeldman/elm-css/blob/1.1.0/src/Css.elm#L4111

**Comment by rtfeldman** [comment]
@jbalboni Ah, good point. I'd intended to expose a `String -> MediaQuery` function and apparently it slipped through the cracks. Sorry about that!

**Comment by rtfeldman** [comment]
Should also do the same for the other At-Rules, come to think of it.

**Comment by jbalboni** [comment]
@rtfeldman Looks like this was fixed with #112, so I'm going to close it. Thought I'd tag you in case you wanted to make an issue for working with the other At-Rules.
