### ISSUE TITLE
Would you consider a `raw` function for adding additional properties as a raw string?

### ISSUE THREAD

**Issue by mbylstra** [rtfeldman/elm-css#97]
The idea is something like this:

```
css =
  (stylesheet << namespace "myModule")
    [ (.) Grid
        [ display flex
        , width (px 200)
        , height (px 200)
        ] ++ raw """
        cursor: default;
        border: 3px solid black;
        """
    ]
```

The `raw` function would just spit out raw css, with no type checking. I don't know enough about elm-css to know how this would be implemented. `raw` would return a list of something (I don't know what).

I realise this goes against one of the goals of elm-css, which is of type safety. However, here are two justifications for this approach:

1. It gives the users of elm-css the option of using properties that haven't implemented. Currently `cursor: default| pointer | grabbing | resize-sw` etc is not implemented., there are hundreds (if not thousands?) of css properties and they are constantly being added to the css specification. The elm community is small: it may not be feasible to keep up. I need to use `cursor: default;`. A the moment my options are either to: 
  -  A. wait till the cursor property gets implemented. An issue has been created (https://github.com/rtfeldman/elm-css/issues/90), but it's already 8 days old, so it may take a month before it's implemented. I didn't intend to spend more than a couple of days on the thing I'm working on, so I'd have to go back to using plain old css.
  - B. Implement it and submit a pull request. This is the noble route, but I don't think we should expect all users to have to understand the internals of elm-css. I had a quick go, but I quickly got confused by types such as `Compatible`. The `default` option of `cursor` seems problematic - I'm sure the word `default` is used by other css properties. Even if I did implement it, I'd have to wait until it got accepted and pushed to elm-packages. A raw function would provide an interim option: it could be replaced once the cursor property appears in elm-css.
2. There are two main modes of writing css: implementing someone else's design, and _designing in the browser_. When you implement someone else's design you know in advance the sizes of paddings and borders. When you design in the browser you are constantly tweaking things until you like them. It would be extremely handy to be able to paste in raw css properties from a browser developer tool, and convert them to elm-css once you've settled on a design. This is one advantage of SCSS: the css property syntax is backwards compatible with css.

I'd be happy to implement this. The real question is whether there would be any philosophical objections to having this functionality in elm-css.

**Comment by eeue56** [comment]
You can already do that here - https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L4717

Obviously, you can't do it as a block, but implementing that is trivial:

```elm
blockProperty : String -> List Mixin
blockProperty block =
  String.split "\n" block
    |> List.map (String.split " : ")
   .. etc

```

**Comment by mbylstra** [comment]
Excellent :)
