### ISSUE TITLE
Why is the core Color.Color type not used to define colors?

### ISSUE THREAD

**Issue by mbylstra** [rtfeldman/elm-css#98]
elm-css defines its own `Css.Color` type rather then using the core `Color.Color` type. It also redefines functions such as `rgb` that are defined in the core library. This seems a bit redundant and means you must map between Core color types and Css color types when using Core color types. Is there a good reason for this?

**Comment by rtfeldman** [comment]
Good question! It's to allow supporting `color inherit` and the like.

For example, you can't write a function called `color : Color.Color -> Mixin` that can accept `color inherit` unless `inherit` is a `Color.Color`.

If we go down that road, then to support something like `height inherit`, now `height` needs to (bizarrely) be `height : Color.Color -> Mixin`.

Having said that, `Css.Color` is a record, and it doesn't seem like there's much downside for it to have a field which is a `Color.Color` for mixing purposes. I'm gonna close this, but if you have a use case for that, by all means please open a separate issue! :smile_cat:
